### ISSUE TITLE
[Bug]: "Shift+Y" keybind for admin/host Zeus access does not work unless set manually in vanilla controls

### ISSUE THREAD

**Issue by Drift91** [igorkis-scrts/A3-Antistasi-Plus#100]
### Describe the bug

The pre-2.0 keybind of "Shift+Y" for admin/host Zeus interface seems to not be working. In order to access Zeus you need to set a custom keybind in the vanilla controls other than the default "Y". Manually setting "Shift+Y" in the vanilla controls seems to work as a temporary workaround.

### How to reproduce

Be logged in as admin or be the host.
Reset the vanilla Zeus interface keybind to the default value.
Hit "Shift+Y", the Battle Options menu shows up instead.

### Version

2.0.2

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted, Private dedicated server

### Mods

```html
"-mod=@CBA_A3;@Antistasi Plus 2.0;@RHSAFRF;@RHSUSAF;@RHSGREF;@RHSSAF;@3CB Factions"
```

**Comment by igorkis-scrts** [comment]
Somewhat fixed in 2.1.
