### ISSUE TITLE
[Bug]: Loot box destroyed when unloaded from RHS truck.

### ISSUE THREAD

**Issue by jacojazz** [igorkis-scrts/A3-Antistasi-Plus#101]
### Describe the bug

When we have finished looting with the loot box, we load it into the truck (M1078A1P2) as normal. When using the "Unload Cargo" option, the box comes straight out the back but as soon as it drops to the floor, it plays an exploding animation and the box is unusable/destroyed along with all the loot.

### How to reproduce

Load loot box into the back of a high backed RHS truck (M1078A1P2), then unload cargo. Box will be destroyed.

### Version

2.0.2 (Latest)

### Have you altered the code?

No

### Map

VT7

### What server?

Private dedicated server with Headless client(s)

### Mods

```html
"-mod=@CBA_A3;@Antistasi Plus 2.0;@RHSAFRF;@RHSUSAF;@RHSGREF;@RHSSAF;@3CB Factions"
```

### Additional context

Nothing relevant in any logs or rpt as I think it's just an in-game issue

**Comment by igorkis-scrts** [comment]
Somewhat fixed in 2.1.
