### ISSUE TITLE
[Bug]: CHDKZ attacks not spawning any AI

### ISSUE THREAD

**Issue by czartrak** [igorkis-scrts/A3-Antistasi-Plus#102]
### Describe the bug

No CHDKS units spawn whenever we have tried to start attacks on cells, some units/carbombs/props spawn occasionally, but its extremely inconsistent

### How to reproduce

Not entirely sure. the mission locations do belong to our faction, however

### Version

2.0.2

### Have you altered the code?

No

### Map

Livonia

### What server?

LAN Hosted

### Mods

```html
CBA_A3
WMO - Walkable Moving Objects
JSRS Soundmod
RHSUSAF
RHSAFRF
Remove stamina
Zeus Enhanced
RHSSAF
RHSGREF
Automated Ace No Medical
Enhanced GPS
Enhanced Movement
Ladder Tweak
JSRS Soundmod - Reloading Sounds
Incon Effects Mod
Blastcore Edited (standalone)
Blastcore Tracers A3 - FoxFort Edit
JSRS Soundmod - RHS AFRF 
Advanced Vault System Remastered
DUI - Squad Radar
Remove Stamina ACE 3
Remove Stamina and Fatigue
Freestyles Crash Landing
Improved Craters
Zeus Enhanced - ACE3 Compatibility
ACE Compats - RHS Compats
3CB Factions
JSRS Soundmod - RHS GREF
JSRS Soundmod - RHS USAF
Antistasi Plus 2.0
```

### Additional context

We were able to complete one or two attacks, but any further have failed to spawn

**Comment by igorkis-scrts** [comment]
Somewhat fixed in 2.1.
