### ISSUE TITLE
[Bug]: Access violation when hosting game

### ISSUE THREAD

**Issue by Notyouraveragefrog** [igorkis-scrts/A3-Antistasi-Plus#103]
### Describe the bug

The game crashes after some time without any warning. Nothing "special" happens when it crashes and I get the access violation message.

### How to reproduce

I dont know. It just happens after some time.

### Version

2.0

### Have you altered the code?

No

### Map

Chernarus 2020

### What server?

LAN Hosted, Private dedicated server, Private dedicated server with Headless client(s)

### Mods

```html
Arma 3 Mods
To import this preset, drag this file onto the Launcher window. Or click the MODS tab, then PRESET in the top right, then IMPORT at the bottom, and finally select this file.

3CB Factions	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1673456286
ace	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE Compat - RHS AFRF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS USAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
ACE Compat - RHS: SAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=2174495332
Antistasi Plus 2.0	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=2912941775
Blastcore Edited (standalone version)	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=767380317
Blastcore Tracers A3 - FoxFort Edit	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=647768227
CBA_A3	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CUP Terrains - Core	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
CUP Terrains - Maps	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=583544987
CUP Terrains - Maps 2.0	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1981964169
Enhanced Movement	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
Interiors for CUP	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1883956552
JSRS SOUNDMOD	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=861133494
JSRS SOUNDMOD - Reloading Sounds	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1429098683
JSRS SOUNDMOD - RHS AFRF Mod Pack Sound Support	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=945476727
JSRS SOUNDMOD - RHS GREF Mod Pack Sound Support	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1180534892
JSRS SOUNDMOD - RHS SAF Mod Pack Support	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1486541773
JSRS SOUNDMOD - RHS USAF Mod Pack Sound Support	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1180533757
Loot to Vehicle for ACE and Antistasi	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1439779114
NSS Admin Console	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=626264195
RHSAFRF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSSAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843632231
RHSUSAF	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
RKSL Studios - Attachments v3.02	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=1661066023
ShackTac User Interface (DISCONTINUED)	Steam	http://steamcommunity.com/sharedfiles/filedetails/?id=498740884
```

**Comment by Notyouraveragefrog** [comment]
[rpt file.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/10530399/rpt.file.txt)

**Comment by igorkis-scrts** [comment]
Seems that it is a general system error:
https://community.bistudio.com/wiki/Arma_3:_Unusual_Process_Exit#0xC0000005_-_ACCESS_VIOLATION

I would start with checking game files integrity, updating server drivers-software and checking OS health via various Windows commands and guidelines (sfc-scannow etc).
Also memtest run to check if your RAM sticks are corruped would be good too.

**Comment by Notyouraveragefrog** [comment]
I think it has to do something with the savegame, because starting a new game works just fine and there arent any crashes (tested it for 20? mins). Is there a way to "repair" the savegame?

**Comment by igorkis-scrts** [comment]
Likely your save file is more late in terms of game progress where it becomes more taxing to hardware, beginning of the game is pretty chil thus problem is not showing itself.
There is a way to repair game - overwrite saveable variable with different value, but then you needs to know which value brings this issue to you and since it is loading just fine and crashes some time later, I don't know if there is a way to know which one causes problem to you and if it will help at all.

**Comment by igorkis-scrts** [comment]
Little update: it's the third case with crash. Have you tried to play with only necessary mods (CBA_A3, CUP Terrains - Core, CUP Terrains - Maps 2.0, 4 RHS mods and 3CB Factions in your case) to see if issue persists?
The only shared thing between cases I noticed is the usage of CUP Terrains - Maps and Interiors for CUP on Chernarus 2020 terrain

**Comment by Notyouraveragefrog** [comment]
I didnt try that yet. But disabling  Interiors for CUP makes sense since I'm playing on Chernarus 2020. I will try that as soon as I'm at home. I will you an update.

**Comment by Notyouraveragefrog** [comment]
So I tested a dedicated server without Interiors for CUP for about 30 mins now and I didnt get a crash. I think this mod was the reason.

**Comment by igorkis-scrts** [comment]
Guess then I'll close the issue. 😅
