### ISSUE TITLE
[Feature Request]: Portuguese localization

### ISSUE THREAD

**Issue by caiotracera** [igorkis-scrts/A3-Antistasi-Plus#105]
### Related problem

Hey, people!
The ArmA has a faithful Brazilian community, and recently I noticed that the Antistasi mission has become very popular to play with friends in a small group. But, since only a small part of the country can speak English, most of the Brazilian players can't fully understand the mod and the missions.

Most of the time I have to translate the texts on the screen, so they can understand what's going on. Because of that, I would like to request (and make myself available) to make the localization of the mission to Portuguese.

### Proposed feature

Add Portuguese localization.

### Additional context

In case you don't mind, I can work on this issue myself.

**Comment by igorkis-scrts** [comment]
The mission texs are 99.99% exposed for localization via various `Stringtable.xml` files. Since there is no way I could make Portuguese localization (as I'm solo developer and don't speak Portuguese), you could make a pull request with localization and it will be merged and then will be released with the next version.

**Comment by caiotracera** [comment]
Hey, @igorkis-scrts!
I'll work on this issue, then! Thank you for the quick answer 💖

**Comment by igorkis-scrts** [comment]
@caiotracera 
Hello! I have plans to release 2.1 update in a matter of one-two weeks. 
If you're still working on a localization and it will be soon ready, it could be packed with this update.

**Comment by igorkis-scrts** [comment]
Closing as stale.
