### ISSUE TITLE
[Change Request]: ChDKZ Mortars HQ

### ISSUE THREAD

**Issue by Dabako** [igorkis-scrts/A3-Antistasi-Plus#112]
### Is the requested change related to a problem?

ChDKZ Mortars HQ very often, when players are AFK. Maybe add an exclusion Zone for ChDKZ Attacks, so it wont attack HQ?

### Describe the solution you'd like.

That ChDKZ won't attack the HQ anymore

**Comment by igorkis-scrts** [comment]
They're attacking it only on omnipresent activity level and it's intentional.
