### ISSUE TITLE
[Feature Request]: Sell All button for Dealer

### ISSUE THREAD

**Issue by FuckingStealingNames** [igorkis-scrts/A3-Antistasi-Plus#114]
### Related problem

Selling items with huge quantities becomes a frustrating task, add with host lag, and item sorting becomes even worse.

### Proposed feature

It'd be a nice addition to have for selling an entire selection of an entity (like a loot box) as a button to avoid this entire frustration.
Also saves time.

**Comment by igorkis-scrts** [comment]
Unfortunately, but Arms Dealer store relies on the third-party HALs Store framework and I have no idea how to do anything there, so while this is an good idea for improvement, likely it will be not done.
