### ISSUE TITLE
[Bug]: Building Structures is free with A.I.

### ISSUE THREAD

**Issue by FuckingStealingNames** [igorkis-scrts/A3-Antistasi-Plus#115]
### Describe the bug

If playing as anything but Commander or Engineer, attempting to construct with A.I. will result with it being entirely free.

This is ONLY true if you take over the Engineer A.I., and not have it walk to the construction icon.

### How to reproduce

1. Be anything but the commander or engineer yourself
2. Place a blueprint of a structure whilst having an A.I. engineer in your squad
3. Take over the engineer yourself instead of letting it walk over to the icon
4. Profit

### Version

2.1.2

### Have you altered the code?

No

### Map

Takistan, Altis, mostly likely every map

### What server?

LAN Hosted, Private dedicated server

### Time bug occured (Server time/UTC)

N/A

### Mods

```html
Antistasi Plus	Steam	https://steamcommunity.com/sharedfiles/filedetails/?id=2912941775
```

**Comment by igorkis-scrts** [comment]
Thanks for report, I'll take a look.
