### ISSUE TITLE
[Bug]: AI not use some anti tank rocket launcher via custom loadout with RHS mod 

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#116]
### Describe the bug

Arsenal remove all ammo come with all gun that include anti tank rocket launcher when use custom loadout with RHS mod weapons like AT-4 ,M72 , RPG-18 etc  don't have ammo in launcher and AI inventory (it can't be added) that make AI think they are no ammo they not use it.

note that I found out RHS rocket launcher will give ammo to player inventory when player hold rocket launcher on hand (AI don't they think they are no ammo).
tested with CUP weapons mod if Player have anti tank rocket launcher they will automatic get ammo in rocket launcher, AI use rocket launcher on CUP weapons mod

### How to reproduce

1.use RHS mod set .
2.set custom loadout give M136 , M72 , RPG-18 .. any rocket launcher that fire and drop to AI.
3.buy that AI
4.test spawn enemy vehicle near AI that give rocket launcher.

### Version

2.4.2

### Have you altered the code?

No

### What i have changed

```markdown
Steam version no change
```

### Map

altis

### What server?

LAN Hosted

### Mods

```html
<html>
<body>
<!--StartFragment-->

RHSUSAF | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=843577117
-- | -- | --
RHSAFRF | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=843425103
CBA_A3 | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=450814997
Enhanced Movement | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=333310405
JSRS SOUNDMOD | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=861133494
JSRS SOUNDMOD - Reloading Sounds | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=1429098683
RHSGREF | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSSAF | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=843632231
Enhanced Movement Rework | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=2034363662
Zeus Enhanced | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=1779063631
3CB Factions | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=1673456286
CUP Weapons | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=497660133
Antistasi Plus | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=2912941775
Ace - No Medical | Steam | https://steamcommunity.com/sharedfiles/filedetails/?id=2236821403

<!--EndFragment-->
</body>
</html>
```

**Comment by igorkis-scrts** [comment]
This is how RHS coded this thing so I can't really do anything about it. The only workaround I know of is to put ammo for their disposable launchers into their backpacks.

**Comment by asumadelta** [comment]
after test with your suggestion, disposable launchers ammo can be added but it just not show in inventory that you have added ammo  it say 0 but ammo it added and work!

**Comment by igorkis-scrts** [comment]
It's not showing because AI" is "charging" that added charge into tube. DIsposable launchers are made with pretty hacky way in both RHS/CUP, they still need ammo to fire.

**Comment by asumadelta** [comment]
What I found it I add ammo 10 time and arsenal say 0 , but when save and look in to inventory they are 10 ammo in there lol maybe this case close or something but thank you for your advice
