### ISSUE TITLE
[Bug]: Commander transferred to AI

### ISSUE THREAD

**Issue by Xestiny** [igorkis-scrts/A3-Antistasi-Plus#117]
### Describe the bug

(Doesnt happen often)
So while I'm playing as the commander and take control of an AI while I'm down, commander sometimes get transferred to the AI I'm controlling which results in having to run the force commander script or restart the server.

### How to reproduce

Take control of AI while dead I suppose?

### Version

2.1.2

### Have you altered the code?

No

### Map

Sehreno

### What server?

Private dedicated server

**Comment by igorkis-scrts** [comment]
Hi! 
To properly investigate your bug, I need to have an .rpt log containing strings with AI direct control with the problem and full modset you're using too.

**Comment by SgtGrumbles** [comment]
@Xestiny I've experienced the same (and logged it here too). Can you provide more details on this "foce commander script", or share it here? I tried a couple commands online to try and return the commander role to myself, but couldn't get it working.

**Comment by igorkis-scrts** [comment]
Closing this as potentionally unsolvable. I tried to do something with it in 2.1.3, but not sure if it will fix this problem, as it's not reproducable in my environment.
