### ISSUE TITLE
Unnamed items on the black market

### ISSUE THREAD

**Issue by nhkun** [igorkis-scrts/A3-Antistasi-Plus#12]
**Describe the bug**
There is a large list of unnamed items in the arms dealer menu

**To Reproduce**
1: Find arms dealer (either by finding intel, or by map settings)
2: Open weapons menu

**Expected behaviour**
All items are named and buyable

**Screenshots**
![20201210031800_1](https://user-images.githubusercontent.com/50690358/101720660-bf31f000-3ad8-11eb-8dae-ddf463a0152e.jpg)
![20201210031826_1](https://user-images.githubusercontent.com/50690358/101720662-c0631d00-3ad8-11eb-8be6-e710f8a36bd1.jpg)

**Environment (please complete the following information):**
Version: 1.2 -- 1.4
Map (specify if Altis Blufor): 
Antistasi Plus - Taviana

Private dedicated server with Headless client(s)

Modset:

3CB Factions | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1673456286
ace | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=463939057
ACE Compat - RHS Armed Forces of the Russian Federation | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773131200
ACE Compat - RHS United States Armed Forces | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=773125288
ACE Compat - RHS: GREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=884966711
Advanced Towing | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=639837898
Arma 3 Taviana 0.4.2 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1333620906
BettIR (Development/Alpha) | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=2260572637
CBA_A3 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
CUP Terrains - Core | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583496184
CUP Terrains - Maps | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=583544987
CUP Terrains - Maps 2.0 | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1981964169
LAMBS_Danger.fsm | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1858075458
Loot to Vehicle for ACE and Antistasi | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1439779114
RHSAFRF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
RHSGREF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSUSAF | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
VET_Unflipping | Steam | http://steamcommunity.com/sharedfiles/filedetails/?id=1703187116

**Comment by igorkis-scrts** [comment]
Reproduced.
This weapons are from RHSSAF which is not presented in your modset.
