### ISSUE TITLE
[Bug]: When downed as commander, if use the "T" key to become AI, die, use "T" again, and revive the former AI, lose commander ability

### ISSUE THREAD

**Issue by SgtGrumbles** [igorkis-scrts/A3-Antistasi-Plus#121]
### Describe the bug

First off, Antistasi Plus is great. Thanks for the work. I'm running a linux server with ACE (no medical). I'm logged in as admin and am commander. I've seen this problem with both Server Memebership on and off.

As commander with a squad of AI, if I die, I can use the "T" key to become an AI. This is an amazing feature, love it. If I find my original body and rez it, things seem to work fine. 

If that AI also goes down, I will return to my original (downed) body, as expected, again with the "R to respawn, T to takeover AI" message. If I hit "T" again, I can become another AI. This is as-expected and works.. I even believe I can use this 2nd AI to find my original body, rez it, and everything is great.

However, while controlling this second AI, I came across the downed AI I was previously controlling, and rez'ed him. The game acted like that AI was my original body: the messaging was if my original player body was rez'ed, the squad control bar appeared (where you can select squad members with the F-keys), etc.

NOTE: it's very possible this only occurs when my original body is fully dead, not possible to revive.

The major problem is that the commanding becomes bugged. It's like I'm sort of the commander, but also not really. The stats bar at the top, for example, doesn't show FIA money. I also critically cannot save at the map: it changes from "Persistant Save" to "Personal Save". I oddly can open some menus that would normally be commander only, but I can do any of the actions ("that requries commander").

Unfortunately, I cannot find a way to restore the commander role to myself. It's presumably got lost in the shuffle when this happened, and maybe the game thinks there still is a commander.. it's just not me. "#logout" and "#login" don't fix anything, nor does "Vote Admin" from the map screen. Exiting the game fully and rejoining also don't fix it. Only a full server restart seems to solve it.

I love the "T" ability to get back in the fight with your AI and revive you, but I'm leery of using it as this has happened a number of times.

### How to reproduce

This has happened a number of times, and I apologize for not knowing the exact steps to make it occur.

Yesterday, though, the chain of events seemed most obvious:

1. Controlling a squad of say 2 AI ("AI 1" and "AI 2"). I'm antistasi commander, server admin. No other players logged in. 
2. I get hit. I use the "T" key to become AI 1. While moving around as AI, I can see my original body is moving around, and revivable.
3. Before I have a chance to revive my original body, AI 1 also gets hit.
4. I return to original body, still downed. I again hit "T" to become AI 2.
5. Original body gets hit by HMG. Fully dead, not revivable.
6. I come across AI 2, and revive him.
7. As soon as AI 2 is revived, I become AI 2, but as if I was the squad leader:  the AI squad bar returns, I can issue orders, etc.
8. I'm now longer commander. I cannot become commander. Commander role seems "stuck" with original body, now lost?
9. I'm fairly sure, although would have to verify, that oddly some commander menus are still available, ones you'd never be able to access as a non-commander player, but I can't actually do anything. 

### Version

2.1.2

### Have you altered the code?

No

### Map

Vt7

### What server?

Private dedicated server

### Mods

```html
ACE (no medical)
```

**Comment by igorkis-scrts** [comment]
This problem is known and, unfortunately, likely to be non-fixable because of game/engine limitations - AI control works through `selectPlayer` command and this command basically moves you from your slot-unit from game lobby with tied game logic to another runtime created one (AI unit which was spawned by various game systems). 
So, to prevent situations like this to happen, there are two event handlers to immideately return your to your body in case of any damage either you or controllable unit takes (Hit EHs are executed earlier than Killed), this is why it shouldn't happen, but it seems that some mod might mess up with. 

Try to play and use this feature without ACE and whatever mods you're using except terrain and content ones (RHS etc) to see if issue persists. I think that ACE No Medical might be the source of the issue, I heard that it actually reduces stability of Antistasi in some other cases.
Unfortunately, if this thing will happen often (this is second reported case about it), I'll remove this feature as unreliable.

**Comment by igorkis-scrts** [comment]
Also, seems that 2.12 Arma 3 update broke something, because your original body shouldn't moving around at very least.

**Comment by igorkis-scrts** [comment]
I'll take a look though as it seems to be repeatable-reproducable.

**Comment by igorkis-scrts** [comment]
Can't reproduce the issue by following these steps.

**Comment by SgtGrumbles** [comment]
Appreciate you looking into it. Sounds basically the same as #117 and #118, and an issue due to engine limitations on `selectPlayer`. 

The biggest problem is loss of commander control. Sounds like the user who submitted #117 has a way to force getting the commander role back; I'll try that.
