### ISSUE TITLE
[Bug]: Невозможно поднять себя ботом после поражения.

### ISSUE THREAD

**Issue by forward-82** [igorkis-scrts/A3-Antistasi-Plus#124]
### Describe the bug

С крайним обновлением армы не всегда получается поднять себя ботом, так и продолжаешь лежать как бы вылеченным но ничего сделать не можешь. Только если другой игрок снова ранит и поднимет лечение срабатывает.
[Arma3_x64_2023-03-01_22-07-39.zip](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/10868686/Arma3_x64_2023-03-01_22-07-39.zip)

### How to reproduce

Когда поднимаю себя ботом через "Т"

### Version

2.1.2

### Have you altered the code?

No

### Map

Napf

### What server?

LAN Hosted

### Mods

```html
RHS AFRF, RHS GREF, RHS USAF, RHS SAF, 3CB Factions
```

**Comment by igorkis-scrts** [comment]
Попробовал что-то сделать с этим, посмотрим, как будет в следующем патче, но я бы особо не надеялся, потому что проблему мне так отловить и не удалось.
