### ISSUE TITLE
[Feature Request]: ACE arsenal

### ISSUE THREAD

**Issue by Alexandre425** [igorkis-scrts/A3-Antistasi-Plus#125]
### Related problem

Playing with a decent amount of mods means the arsenal becomes incredibly cluttered.

### Proposed feature

The ACE arsenal's search feature and functional filters make finding what you're looking for a lot easier.

### Additional context

I don't know how feasible it is, and if the ACE arsenal has support for a limited number of items, but it certainly would be a very welcome feature.

**Comment by igorkis-scrts** [comment]
Well, Antistasi uses highly customized Jeroen Arsenal and full rewriting could take a *really* lot of time and could be an easily an separate mod itself.
If we're talking about just integrating ACE arsenal, it can't be easily done as:
1. It should be properly integrated into Antistasi's gameplay systems and the amount of work here is really big. 
2. It will be either two arsenals existising simultaneously and it will double the code to support or will introduce hard ACE dependency/requirement which I want to avoid.

While I'm not satisfied with the current arsenal state and it really should be done better, unfortunately, it will be not done at very least by me as Antistasi Plus and Arma 3 are pretty late into their respective lifecycles.

**Comment by Alexandre425** [comment]
Yeah, I thought that might be the case, I understand
