### ISSUE TITLE
[Feature Request]: Donating to the faction in bigger amounts

### ISSUE THREAD

**Issue by FuckingStealingNames** [igorkis-scrts/A3-Antistasi-Plus#126]
### Related problem

With how you can gain massive profits by selling to the black market dealer, a small amount of 100 becomes completely terrible to spam to donate to the faction.

### Proposed feature

Having a bigger amount deposit button, maybe 1,000, would be perfect.

**Comment by igorkis-scrts** [comment]
Will be somewhat addressed in the next patch (although it will be not 1000 amount).

**Comment by FuckingStealingNames** [comment]
thank you for this information.
