### ISSUE TITLE
[Bug]: Server stuck on "Waiting for server"

### ISSUE THREAD

**Issue by Artycular** [igorkis-scrts/A3-Antistasi-Plus#127]
### Describe the bug

You hop into a game, and the server is stuck forever on "Waiting for Server". The RPT Log is attached below.

### How to reproduce

hop into the server and it just happens?

### Version

2.1.3 and earlier.

### Have you altered the code?

No

### Map

Chernarus 2020

### What server?

Private dedicated server

### Mods
-

### Additional context

[arma3server_2023-03-06_05-35-25.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/10899088/arma3server_2023-03-06_05-35-25.txt)

**Comment by fire** [comment]
Hi I am @fire.

**Comment by igorkis-scrts** [comment]
>  5:39:30 2023-03-06 13:39:30:015 | Antistasi | Info | File: A3A_fnc_initServer | Server version: 2.0.2.6bc5c4c
As usual - it's because you're using old version of Antistasi Plus while your clients are using most recent version (2.1.3). Also, seems that you're not enforcing `verifySignatures` parameter thus allowing to join any person with any modset and it is really dangerous for your server as some mods may execute the code other players don't have thus allowing to break the mission.

**Comment by igorkis-scrts** [comment]
Lol, it seems that Github treats mod names as mentions. OP, please, fix your post.

**Comment by Artycular** [comment]
@igorkis-scrts This can't be man, i literally just re-downloaded the mod on the server two times, same result..

**Comment by igorkis-scrts** [comment]
Log clearly states that's the server is on 2.0.2.
>  5:39:30 2023-03-06 13:39:30:015 | Antistasi | Info | File: A3A_fnc_initServer | Server version: 2.0.2.6bc5c4c****

**Comment by igorkis-scrts** [comment]
Closing this as this issue is not tied to Antistasi Plus codebase. 
Download latest .pbos and do a full reinstall of mod:
https://github.com/igorkis-scrts/A3-Antistasi-Plus/releases/tag/v2.1.3
