### ISSUE TITLE
[Change Request]: Increase the clickable radius of outposts on the map

### ISSUE THREAD

**Issue by Alexandre425** [igorkis-scrts/A3-Antistasi-Plus#129]
### Is the requested change related to a problem?

Selecting outposts on the map is difficult, especially when it's zoomed out.

### Describe the solution you'd like.

Increasing the radius the player can click to select an outpost would help. Even better if the radius was relative to the map's zoom.

**Comment by igorkis-scrts** [comment]
Unfortunately, but there is no way to get map zoom level and current fixed click radius check is depending on that. 
Game/engine limitation, so not much can be done there.
