### ISSUE TITLE
Grab 100 and 1000 from faction funds buttons.

### ISSUE THREAD

**Issue by StevenTheNemo** [igorkis-scrts/A3-Antistasi-Plus#13]
**Is your feature request related to a problem? Please describe.**
Currently the grab faction funds button is at 1000, which is great except at the very start of a mission where it's possible to accidentally go under 1000 and thus be unable to supply any vehicles for the team since you can't take any funds out for even the cheapest vehicle. Some HQ start locations are also very far from any civilian traffic thus making the start very tedious having to walk through a forest for an hour every time you die.

**Describe the solution you'd like**
Having two separate 100 and 1000 buttons, or if menu space is limited perhaps having one 500 funds button, enough to get the group started and still be more significant than 100.

**Additional context**
Walking for 10 minutes to just be perforated by an M2 is not the most fun gameplay

**Comment by igorkis-scrts** [comment]
Fixed in 1.4.1.
