### ISSUE TITLE
[Bug]: If air support vehicle is destroyed, air support menu completely stops working until server restart

### ISSUE THREAD

**Issue by JarnoKai** [igorkis-scrts/A3-Antistasi-Plus#130]
### Describe the bug

When ordering support, be it a recon plane or loot helicopter, if the vehicle gets shot down before the support is completed, the support is never deemed complete and the server doesn't let you order any more support for the remainder of the game. The server must be restarted for support to be available again - dying, changing commanders or reconnecting doesn't fix the issue.

### How to reproduce

Order air support, eg. recon plane and have the enemy (or I suppose you could do it yourself as well) shoot it down before it completes its mission. The support menu no longer allows you to place destination markers.

### Version

2.1.4

### Have you altered the code?

No

### Map

Tanoa and Livonia

### What server?

LAN Hosted, Private dedicated server with Headless client(s)

**Comment by igorkis-scrts** [comment]
Include server .rpt log so the issue could be properly investigated.

**Comment by JarnoKai** [comment]
I attached a log file.
At around ~18:30:00 I summon a recon plane and shoot it down the moment I see it. Surprisingly this time the support system continued working after - that was the first time I saw a plane being shot down without breaking the system completely.
At around ~18:33:00 I summon a loot helicopter and shoot it down as it was about to land. The ropes disappear and the loot box drops freely. The markers stay on the map for a short while and then disappear after about a minute. No markers can be added to the support menu afterwards and the reset button doesn't do anything.
[airsupport.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/10922894/airsupport.txt)

**Comment by igorkis-scrts** [comment]
Well, log doesn't contains any script errors or Antistasi error logs,  so it seems that it's not a script logic error and most likely logic pitfall that leads to this  issue.

**Comment by igorkis-scrts** [comment]
Yeah, it seems to be the case. I'll hotfix it rn.

**Comment by igorkis-scrts** [comment]
Hotfixed in 2.1.5.
