### ISSUE TITLE
[Change Request]: Move the arms dealer in the Takistan map

### ISSUE THREAD

**Issue by Alexandre425** [igorkis-scrts/A3-Antistasi-Plus#132]
### Is the requested change related to a problem?

Fast traveling to the arms dealer in Takistan places the player ~1km away, with a giant mountain in the way. This makes it very hard to take a vehicle with which to carry items.

### Describe the solution you'd like.

Moving the arms dealer closer to a road would fix this.

### Alternative solutions

Allowing the player to relocate the arms dealer would also be a nice solution.

**Comment by FuckingStealingNames** [comment]
you can relocate it, gotta spend 1,000 of a currency to reroll your chance for a better spot

**Comment by Alexandre425** [comment]
Oh, I haven't come across that, where is that option?

**Comment by igorkis-scrts** [comment]
You can reroll AD location via Commander Menu (About tab). 
There was an mechanic of moving trader to HQ, but it had some serious bugs thus it was removed.
