### ISSUE TITLE
CZ 584 Shotgun unlocked with no ammo

### ISSUE THREAD

**Issue by Savage117** [igorkis-scrts/A3-Antistasi-Plus#14]
When starting a fresh game on Chernarus 2020, with the CUP modset loaded, your arsenal starts with two guns unlocked without ammo available, the CZ 584 and the CZ 584 (RIS), screen shot below. When equipping one of the guns and going to a container to put it in, clothing, vest, etc. a incompatible ammo type is shown, (7.62mm  1Rnd CZ 584 (Ball) ammo) screen shot below. As far as I have been able to determine this ammo isn't lootable and it can't be bought from the Arms Dealer. 

**To Reproduce**
Load up a fresh Antistasi Plus game on Chernarus 2020, no other maps tested, with CUP Weapons, Units, Vehicles, Maps 2.0 and their dependencies. Look in the arsenal primary weapon section. This happens with and without DLCs loaded in the parameters, or the parameters left on default or changed. 

**Expected behaviour**
I expect the two guns to start with the appropriate ammo unlocked and infinite like the other starter guns.

**Screenshots**
Weapon List:
![20201215114547_1](https://user-images.githubusercontent.com/38669605/102267556-f0426400-3ece-11eb-94c2-0978ba80d0fd.jpg)

Available Ammo list:
![20201215114857_1](https://user-images.githubusercontent.com/38669605/102267621-0bad6f00-3ecf-11eb-9852-37327de38c4d.jpg)

**Environment (please complete the following information):**
Version: 
Launcher version: 1.5.146773

Game version: 2.00.146773

Branch: main / beta branch not specified

Map (specify if Altis Blufor): Chernarus 2020, playing Greenfor

* [X] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
CBA_A3
CUP Terrains-Core
CUP Weapons
CUP Units
CUP Vehicles
CUP Terrains-Maps 2.0
    
Time the bug occurred (Please leave in GMT+0):
N/A

**Additional context**
N/A

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

[Arma3_x64_2020-12-15_11-38-03.zip](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/5698377/Arma3_x64_2020-12-15_11-38-03.zip)

**Comment by igorkis-scrts** [comment]
CZ 584 is bicaliber weapon - basically, one barrel is smoothbore and the second one is rifled (use F to switch between them). Both ammo types are there, but one of them stored in list that can be accessed through three mags icon button.
