### ISSUE TITLE
[Change Request]: Update Schedule

### ISSUE THREAD

**Issue by Dabako** [igorkis-scrts/A3-Antistasi-Plus#144]
### Is the requested change related to a problem?

Currently you update the mod on the steam workshop, nearly daily. I am very happy that you work on that mod and make it better and fix bugs. 

The problem is that, if mods get updated daily. Server users have to update the mod daily too. In my case it is kinda high workload to do that. 

### Describe the solution you'd like.

Maybe an idea could be an 1 release a week schedule. So that you pack several fixes over the course of a week and then release them together like every tuesday. 

For example: 2.1.5 2.1.6 2.1.7 2.1.8 together as one update instead of several. 

It is just a suggestion and I do understand that it is your mod and you can decide how to release your updates.
Just wanted to put some input!

**Comment by igorkis-scrts** [comment]
Yeah, I know about how updates are affecting server admins.
I think that the mod is finally stabilized and there will be no frequent updates that will cause such headache.
