### ISSUE TITLE
[Bug]: Black screen isn't removed when "something went wrong" during paradrop plane start

### ISSUE THREAD

**Issue by JarnoKai** [igorkis-scrts/A3-Antistasi-Plus#145]
### Describe the bug

When starting a paradrop plane run and the run fails for some players, the black timer screen is not removed. Getting rid of the black screen requires aborting the mission.

### How to reproduce

For some reason, at least for us, paradrop plane fails if more than two players are in HQ with paradrop enabled. The starting screen appears for all players, but only two are put in the plane. A "something went wrong" notification appears for the remaining players and they get stuck in the black starting screen.

### Version

2.1.9

### Have you altered the code?

No

### Map

Tanoa

### What server?

LAN Hosted, Private dedicated server with Headless client(s)

### Additional context

I checked the code. In A3A/addons/scrt/Paradrop/fn_paradrop_movePlayerToPlane.sqf row 82-84:
```
if (_earlyEscape) exitWith {
    [localize "STR_A3AP_paradrop_header", localize "STR_A3AP_paradrop_abort_plane_something_wrong"] call SCRT_fnc_misc_deniedHint;
};
```
The script exits by only showing the notification to the player. The black screen is only deleted with a "BLACK IN" cutText on row 88:
`cutText [localize "STR_cut_text_paradrop_notification_3","BLACK IN", 3, true, true];`
This line is never reached under the "earlyEscape" situation.

**Comment by igorkis-scrts** [comment]
Somewhat addressed/fixed in 2.1.10.
