### ISSUE TITLE
[Change Request]: Добавить NATO'вский истребитель танков в их темплейты

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#156]
### Is the requested change related to a problem?

нет

### Describe the solution you'd like.

Добавить натовские истребители танков в airborn vehicles

### Alternative solutions

нет

### Additional context

Rhino MGS и Rhino MGS UP  (это так истребители называются) вмещаются в v-44 x которые используются в теплейте. Есть возможная проблема с балансом, но у Rhino ведь есть прописанная цена, соответственно ИИ не будет ими спамить.

**Comment by igorkis-scrts** [comment]
Они уже используются в vehiclesLightTanks-секции.
```sqf
if (_hasTanks) then {
    _lightTanks append ["B_AFV_Wheeled_01_cannon_F","B_AFV_Wheeled_01_up_cannon_F"];
};
```

**Comment by wersal454** [comment]
Ааа. Может стоит добавить в QRFVEHAIRDROP легкие танки и _lightarmed они все(по большей части) помещаются в самолёты, соответственно могут быть сброшены. Также можно проверку добавить на уровень войны. И по поводу транспортных сидений, самолёт ведь сбрасывает отдельно технику и пехоту(которая вроде как не идёт к технике чтобы в неё залезть, а сразу рвётся в бой) соответственно нет необходимости парится по поводу количества сидений

**Comment by wersal454** [comment]
А ну и собственно почему бы не спавнить технику в воздухе уже с пехотой внутри, а не в самолёте. Это конечно может быть нереалистично, хотелось бы услышать твоё мнение по этому поводу.

А ещё таким образом можно добавить проверку на кол-во доступных мест и расширить пул совместимой с этой функцией техники (a.k.a легкие танки, _lightarmed и т.д.)

**Comment by wersal454** [comment]
> Они уже используются в vehiclesLightTanks-секции, в Airborne не могут быть добавлены потому что у них нет транспортных сидений.
> 
> ```sqf
> if (_hasTanks) then {
>     _lightTanks append ["B_AFV_Wheeled_01_cannon_F","B_AFV_Wheeled_01_up_cannon_F"];
> };
> ```

// airborne vehicles, could be with passenger seats or just a crew это из твоего описания к этому классу техники

**Comment by igorkis-scrts** [comment]
Вообще, возможность расширения пула десантируемой техники звучит неплохо, я подумаю над этим.
Но тогда придётся, вероятно, отказаться от спавна внутри техники. Я этот код писал давно, возможно, причиной отдельного спавна пехоты послужило то, что технику можно подбить из гранатомета пока она падает на парашюте вместе со всем десантом, что было слишком легко.
