### ISSUE TITLE
[Bug]: ВОЗМОЖНЫЙ БАГ с установками SAM

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#157]
### Describe the bug

Заметил что SAM установки иногда не работают (или вообще не работают точно не помню)

### How to reproduce

Пролететь рядом с базой в надежде что по тебе выстрелит именно SAM а не товарищи с гранатомётами или ПВО техника

### Version

Майская версия(подозреваю что проблема до сих пор есть)

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted

### Additional context

Скорее всего SAM не работают из-за того что радарные установки по умолчанию не включают собственно радар

Можешь проверить это путем захвата радарной установки и подключением к ней, на экранчике сенсоров который открывается через "[" или "]" увидишь что радар выключен

**Comment by igorkis-scrts** [comment]
Да, действительно, возможно радар либо не включен либо не шарит цели. Попробую что-то с этим сделать в следующем апдейте.

**Comment by igorkis-scrts** [comment]
Проверил. C, по крайней мере, `setVehicleRadar` и `setVehicleReportRemoteTargets` сопровождение целей и стрельба по ним работает, причем на довольно почтительном расстоянии. Спасибо за репорт.
![изображение](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/6746043/b274776b-8966-4d44-888a-b99a1e9f68d9)

**Comment by wersal454** [comment]
@igorkis-scrts А кстати по поводу расстояния и в целом ПВО. Можно сократить его для установок SAM? А то подозреваю играть на воздушной технике станет совсем не весело.

А ещё тоже самое с солдатами с титанами, уж больно часто они ими стреляют. Только подлетаешь куда-нибудь на верте, даже пиликнуть о локе не успевает как в тебя ракета прилетает(может стоит добавить задержку перед выстрелом?). Хотя я подозреваю это ИИ армы такой прикольный

**Comment by igorkis-scrts** [comment]
> Можно сократить его для установок SAM?
Вряд ли, это нужно менять характеристики радара в конфиге. Так как установка спавнится на расстоянии километра по обычным настройкам, это значит, что играть с авиацией по-прежнему будет можно, но не входя в воздушное пространство рядом с авиа- и военными базами, как и было задумано.
