### ISSUE TITLE
[Bug]: В темплейте AUKUS вылазит ошибка "missing plate_carrier_v2"

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#158]
### Describe the bug

В темплейте AUKUS tropical(возможно и в остальных) вылазит ошибка "missing plate_carrier_v2" или как-то так. 

### How to reproduce

Можешь проверить просто выбрав эти теплейты при запуске миссии

### Version

Майская версия(подозреваю что проблема до сих пор есть)

### Have you altered the code?

No

### Map

Tanoa

### What server?

LAN Hosted

### Mods

```html
Aegis
```

**Comment by igorkis-scrts** [comment]
Темплейты Aegis на текущий момент не являются официально поддерживаемыми ввиду того, что они зависят от их Development Branch и с текущей стабильной версией Aegis, соответственно, не работают. Я их переделаю когда Aegis разродится новой стабильной версией.
