### ISSUE TITLE
Prevent Artillery Strike broken payout

### ISSUE THREAD

**Issue by Randomisation** [igorkis-scrts/A3-Antistasi-Plus#16]
The mission is completely broken in terms of balance. You can literally just go undercover, walk up to the artillery, drop an explosive charge and walk away. Enemy AI do nothing. Everyone on the server receives €5000 reward. In less than an hour, we have €100,000 in the bank, which breaks the economy/renders it useless.

Either remove the mission, make the reward as trivial as the mission difficulty, or make the AI actually defend the Artillery.

I'm not entirely sure of how the mechanics work regarding the undercover system, but a simple solution would be to add guard dogs, or make the artillery spawn classed as an outpost. Without knowing how the systems in Antistasi actually work, I am not sure what approach would be best to solve the problem. 

On another, similar note - We have encountered the same issue of AI completely ignoring undercover players when blowing up Radio Towers. AI walk within 2 meters of players setting charges on the tower and do nothing (this was at the dam outpost north of the original spawning point).

**Comment by igorkis-scrts** [comment]
Thanks for report. 
This is a bug, not an oversight. It is already noticed and fixed in 1.4.2, which i might release in 1-2 weeks.

**Comment by igorkis-scrts** [comment]
Fixed in 1.4.2.
