### ISSUE TITLE
[Change Request]: Vanilla AAF template

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#162]
### Is the requested change related to a problem?

нет

### Describe the solution you'd like.

Я заметил что у тебя в теплейте написано ВОТ ЭТО вот: 
private _lightArmed = ["I_MRAP_03_hmg_F", "I_MRAP_03_gmg_F"];
["vehiclesLightTanks", ["I_LT_01_cannon_F", "I_LT_01_AT_F"]] call _fnc_saveToTemplate;
if (_hasTanks) then {
    _lightArmed append ["I_LT_01_AT_F", "I_LT_01_cannon_F"];
Почему у тебя маленькие танки AAF и там и там находятся? Точнее зачем после проверки на наличие dlc ты добавляешь эти танки в lightArmed ?

["vehicleRadar", "I_E_Radar_System_01_F"] call _fnc_saveToTemplate;
Может стоит добавить "I_LT_01_scout_F" или же код написан только под установки с радаром?(сомневаюсь в этом)

private _militiaAPCs = if (_hasTanks) then {["I_LT_01_cannon_F"]} else {[]};
["vehiclesMilitiaAPCs", _militiaAPCs] call _fnc_saveToTemplate;
Вот этого момента тоже не понял. Если есть dlc то легкий танк в категорию БТР(легкий танк у которого всего 2 места, командир и водитель) и если dlc нет то вообще ничего. Может стоит все же добавить I_APC_tracked_03_cannon_F или I_APC_Wheeled_03_cannon_F ?

["vehiclesPlanesTransport", []] call _fnc_saveToTemplate;
Может всё же стоит добавить натовский VTOL сюда? Прежде чем ты напишешь "Нет он ведь натовский" 3 момента.
1. Ты уже используешь установки радар и sam натовские(смотри выше).
2. Думаю всё же стоит добавить хоть какой-то самолёт чтобы функция QRFVEHAIRDROP работала. А то ["vehiclesAirborne", ["I_APC_Wheeled_03_cannon_F"]] есть , а самолёта нет.
3. Траспортные самолёты на авиабазах не спавнятся(кстати почему?) поэтому игроки не смогут залутать натовский самолёт играя против AAF.

### Alternative solutions

нет

### Additional context

нет

**Comment by wersal454** [comment]
Опять таки если согласен со всем перечисленным, но не хочешь сам этим заниматься, я готов помочь.

**Comment by igorkis-scrts** [comment]
> Почему у тебя маленькие танки AAF и там и там находятся? Точнее зачем после проверки на наличие dlc ты добавляешь эти танки в lightArmed ?

Ванилла очень ограничена в выборе ассетов, скорее всего, данный код стал бессмыссленным после добавления категории лёгких танков. Я поправлю.

> Может стоит добавить "I_LT_01_scout_F" или же код написан только под установки с радаром?(сомневаюсь в этом)
`vehicleSam` и `vehicleRadar` используются только для статической ПВО на milbase'ах и airport'ах, не думаю что есть смысл использовать эту машинку потому что сильно сомневаюсь в её возможностях подсвечивать самолёты на дальнем расстоянии.

> Вот этого момента тоже не понял. Если есть dlc то легкий танк в категорию БТР(легкий танк у которого всего 2 места, командир и водитель) и если dlc нет то вообще ничего. Может стоит все же добавить I_APC_tracked_03_cannon_F или I_APC_Wheeled_03_cannon_F ?

В этой категории должен быть легкий БТР с пулеметным вооружением. Если использовать полноценные, с пушкой и ПТУРами, то это повредит балансу и экономике техники у фракции игроков (игроки не должны получать постоянный источник такой мощной бронетехники). Фракции ассиметричны для дарования разного пользовательского опыта при игре на разных картах с разными фракциями с использованием разных модов. 

> Может всё же стоит добавить натовский VTOL сюда? 
Не думаю. Как уже было отмечено выше, фракции ассиметричны и если какого-то подходящего ассета нет, то мне неинтересно собирать из спичек и желудей (сиречь ассетов других фракций) лишь бы было. К тому же, это хорошо ложится на идею что AAF - "нищая" местечковая армия и у них каких-то вещей просто может не быть.

> Ты уже используешь установки радар и sam натовские(смотри выше).
Радар используется ливонский (LDF) Компромиссное решение.

> Думаю всё же стоит добавить хоть какой-то самолёт чтобы функция QRFVEHAIRDROP работала. А то ["vehiclesAirborne", ["I_APC_Wheeled_03_cannon_F"]] есть , а самолёта нет.

Скорее всего, эта категория заполнена на всякий случай чтобы где-нибудь не отвалилось. Антистаси очень большой, поэтому проверить вообще весь код на работоспособность, тем более в одиночку - задача нетривиальная. А вообще, см. ответ ответ про ассиметричность.

> Траспортные самолёты на авиабазах не спавнятся(кстати почему?)
Потому что код спавна никто до этого не написал. Также думаю, что есть проблема с тем что они большие и многие из них поместятся в стандартные тентованные ангары. Заспавнить что-то в Арме чтобы оно не взлетело тут же на воздух - задача тоже нетривиальная. 🙃

**Comment by wersal454** [comment]
Ок. По поводу I_LT_01_scout_F у неё радар на 8 км!(да ещё и на 360 градусов)
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/2bfdc86f-4410-4c3f-94ec-45c33accd649)
 Подумай ещё раз над добавлением. + как ты сам сказал каждая фракция это уникальная снежинка так что, почему бы AAF не выделятся вот таким вот л.т. с радаром?

По поводу мощности этих л.т. они разносятся с пулемёт 50 калибра) "игроки не должны получать постоянный источник такой мощной бронетехники"

Ну и по поводу "Радар используется ливонский (LDF) Компромиссное решение." ну так может всё же добавить радарный л.т. если не хочешь компромисс? Ну а если нет то по такой логике не вижу прям жёсткого повода не добавить VTOL.(К конце концов AAF и NATO по умолчанию блюфоры, может им натовцы за кулисами помогают))

И последний момент по поводу спавна транспортных самолётов: 
1. Им ведь не обязательно спавнится в ангарах (можно и рядом или вообще на полосе(она всё равно не используется))
2. А как собственно определяется что и где спавнится ? Это в карте как-то настраивается или в коде функций? Ответь пж очень уж интересно.

**Comment by wersal454** [comment]
А ещё по поводу л.т. и техники AAF в целом может закинуть их(все варианты и пво и пт и с пушкой и с радаром) в магазин к торговцу? А ещё очень уж не хватает на 9-10 уровне войны возможности купить танк AAF пускай и за 20-30 тысяч или 40. Очень уж у нас много денег было под конец игры на Алтисе. По логике вселенной игры AAF как-то умудрились закупить эти типо леопарды и грифоны и прочее. Ну и вообще чутка разнообразить магазин торговца в плане техники.

**Comment by wersal454** [comment]
А ещё такой вопрос. Зачем собственно существует функция поддержки SAM если идея их добавления в темплейты в том чтобы игроки не подлетали слишком близко к базам?. Просто это получается одна и та же штука реализованная дважды.

**Comment by igorkis-scrts** [comment]
> Подумай ещё раз над добавлением. + как ты сам сказал каждая фракция это уникальная снежинка так что, почему бы AAF не выделятся вот таким вот л.т. с радаром?

Я, в целом, не против, но:
1. Нужно будет допиливать код спавна, потому что текущие ПВО-штуки в коде игры - беспилотные, а в этом пепелаце кто-то должен сидеть. В целом, это не проблема, но это будет буквально 1 (один) такой случай (если исключить дублирование Aegis AAF), стоит ли овчинка выделки?
2. Нужно будет поставить какой-то большой ЗРК в пару к радару, и тут мы опять приходим либо к MIM-145 Defender от LDF, либо ставить аналогичный пепелац, только с ракетами ближнего действия. Но ведь последний уже и так спавнится через `vehiclesAA`-массив.

> По поводу мощности этих л.т. они разносятся с пулемёт 50 калибра)
Дело не в броне, а в огневой мощи и тепловизоре. Стоя где-нибудь за 4-5 км, можно выщелкивать технику ПТУРами и крошить ярко подсвеченную в теплаке пехоту из автопушки. Это, в целом, нормально, но если дарить каждые 20-30 минут по такой машинке через блокпосты и авиадесант - излишне.

> Ну и по поводу "Радар используется ливонский (LDF) Компромиссное решение." ну так может всё же добавить радарный л.т. если не хочешь компромисс? Ну а если нет то по такой логике не вижу прям жёсткого повода не добавить VTOL.(К конце концов AAF и NATO по умолчанию блюфоры, может им натовцы за кулисами помогают))

Я посмотрел код и понял, что лучше добавить отдельных LDF (которым уже можно дать технику НАТО) для ванилки и аегиса, а AAF радар и ЗРК убрать вовсе, раз уж у них нет нужных ассетов.

> Им ведь не обязательно спавнится в ангарах (можно и рядом или вообще на полосе(она всё равно не используется))

К сожалению, на многих картах ВПП не размечена через конфиг карты и её детект - довольно нетривиальная задача. Код на спавн самолётов на ВПП есть, просто он большинстве случаев не работает (особенно на моденных картах), посмотрю что с ним можно сделать.

> А как собственно определяется что и где спавнится ? Это в карте как-то настраивается или в коде функций? Ответь пж очень уж интересно.

См. код`fn_createAiAirplane`, `fn_findSpawnPosition` и `fn_initSpawnPlaces`. В целом, для авиации происходит детект определенных построек (вертолётных площадок, ангаров и так далее) и затем они заполняются ассетами из темплейтов фракций.

> А ещё по поводу л.т. и техники AAF в целом, может закинуть их(все варианты и пво и пт и с пушкой и с радаром) в магазин к торговцу? 
Раньше так было, я удалил возможность покупать потому что купить современный танк или самолёт в магазине слишком уж по-ГТАшному как-то и значительно упрощает экономику предметов и техники. Магазин - это комплементарная игровая механика, а не основная, и она не должна заменять добычу техники и оружия с поверженных врагов, захват и последующий лутинг аутпостов это основная игровая механика в этом плане. По задумке, игрок в магазине может покупать лишь устаревшую технику (в темплейтах RHS+3CBF, например, это старые Т-55, БМД-1 самых простых модификаций и так далее). В ванилке просто совсем немного ассетов.

> А ещё такой вопрос. Зачем собственно существует функция поддержки SAM если идея их добавления в темплейты в том чтобы игроки не подлетали слишком близко к базам?. Просто это получается одна и та же штука реализованная дважды.

SAM как физически существующие объекты появились на полгода-год раньше в моём форке чем появился SAM-тип поддержки (он появился в ходе имплементации системы поддержки в комьюнити-версии). С тех пор они существуют вместе, потому что мне не хочется удалять мой код и потому что, в общем-то, они друг другу не мешают.

**Comment by wersal454** [comment]
А ещё по поводу "...отдельных LDF (которым уже можно дать технику НАТО)...". Как ты считаешь AAF и LDF к кому больше склоняются, к NATO или CSAT? Просто в оригинальной кампании AAF были вместе с CSAT,а LDF и NATO в Contact повздорили из-за недоразумения вызванного [REDACTED].

**Comment by igorkis-scrts** [comment]
Шлемы и костюмы Viper - это меня когда-то попросили друзья добавить в наших поигрушках и оно случайно попало в публичную версию. По-хорошему, их надо удалить для консистенции с концепцией, но так уж и быть, трогать не буду. 🙃

> P.P.S Я планирую добавить в ванильные фракции костюмы гили и маскхалаты(разные вещи) для снайперов и споттеров.
Вообще, я бы не был настолько категоричен как CV насчёт гилли - я бы сделал отдельную категорию костюмов и классы патрульных-снайперов в лесах (control-зонах) чтобы не все снайперы и споттеры ходили мохнатыми.

>  Как ты считаешь AAF и LDF к кому больше склоняются, к NATO или CSAT? Просто в оригинальной кампании AAF были вместе с CSAT,а LDF и NATO в Contact повздорили из-за недоразумения вызванного [REDACTED].

AAF - тру-индепенденты, доедают старую технику нулевых с НАТО, но в НАТО не входят (с-но новую технику не получают) и в кампании с ними воюют. 
LDF - согласно лору в НАТО входят и могут иметь их современную технику, в кампании Контакта они проводят совместные учения Electron-39. 

Вообще, по поводу непоследовательности и странных решений, могу сказать две вещи:
1. Разработка велась итеративно на протяжении трёх лет исключительно в одиночку.
2. Я специально отселился в отдельный форк, чтобы делать вещи в том виде, в котором мне нравятся. Есть "официальная" комьюнити-версия, где все умно и последвательно, а есть мой отдельный форк, который я пилю по настроению и наличию свободного времени. Поэтому не стоит слишком серьезно воспринимать происходящее в нём.

**Comment by wersal454** [comment]
"Вообще, я бы не был настолько категоричен как CV насчёт гилли - я бы сделал отдельную категорию костюмов и классы патрульных-снайперов в лесах (control-зонах) чтобы не все снайперы и споттеры ходили мохнатыми."

Точно такая же идея с отдельными классами костюмов для снайперов(как сейчас есть шляпы для снайперов), но вот всё остальное вообще не понял. Точнее не знаю смогу ли я это реализовать... так что добавление гилли на тебя переходит). Шутка! Могу пока что добавить их классы в темплейты!

"AAF - тру-индепенденты, доедают старую технику нулевых с НАТО, но в НАТО не входят (с-но новую технику не получают) и в кампании с ними воюют."
"LDF - согласно лору в НАТО входят и могут иметь их современную технику, в кампании Контакта они проводят совместные учения Electron-39."
Во время учений произошёл инцидент после которого они начали уже палить в друг друга. Но не суть, я спросил потому что работаю над идеей двойных фракций(темплейтов). Расскажу по подробнее в возможном issue.

"Я специально отселился в отдельный форк, чтобы делать вещи в том виде, в котором мне нравятся. Есть "официальная" комьюнити-версия, где все умно и последвательно, а есть мой отдельный форк, который я пилю по настроению и наличию свободного времени. Поэтому не стоит слишком серьезно воспринимать происходящее в нём."

Я воообще не против, твой мод твоё право. Я только за фан и без строгих ограничений(под фаном подразумеваю большее количество фишек и использование контента по максимуму). Поэтому и закидываю тебя идеями и PRами(за что кстати хотел извиниться! Что-то из меня прям прут идеи. Мне просто очень понравился antistasi и я очень хочу улучшить его как могу. Ну и программистские пальчики размять перед учёбой.)
