### ISSUE TITLE
[Feature Request]: Бронированные авто из Western Sahara для темплейтов ванилы и aegis

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#163]
### Related problem

Я заметил что все ванильные фракции(ну csat точно) используют offroad(пикап) без брони(я так понимаю они находятся в категории militia). Почему бы не добавить им и бронированные варианты?

### Proposed feature

Собственно закинуть в темплейты бронированные offroadы.

### Alternative solutions

нет

### Additional context

Если опять таки если не хочешь заниматься этим сам, я могу это сделать.

**Comment by igorkis-scrts** [comment]
Вообще, они уже добавляются через черный рынок, но на новой версии можно засунуть их в дефолтные массивы и подправить им цену. Ок, добавлю в следующей версии.

**Comment by wersal454** [comment]
Если по дефолтными массивами ты имеешь в виду lightunarmed к примеру то, круто спасибо!

Только не знаю стоит ли их закидывать к militia или вообще везде(скорее всего только к militia потому что это лоу левел техника по сути)

**Comment by wersal454** [comment]
@igorkis-scrts 
Я глянул изменения в обновлении. Я вообще то имел ввиду добавить их в вражеские темплейты в militia.
