### ISSUE TITLE
[Feature Request]: Обновление ванильных карт(Алтис,Таноа,Мальден и карта из Western Sahara)

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#164]
### Related problem

Заметил что в community version иногда используются чисто вертолётные базы. Может добавить такие же? В CV эти базы отмечены как авиабазы и я уже вижу проблему в виде баланса, но я думаю можно что-то придумать.

Также есть идея по добавлению авианосцев и дестроеров в местах коридоров поддержки на Алтисе,Таноа и Мальдене.

### Proposed feature

Добавить вертолётные базы собственно

Суть добавления кораблей: 
Когда функция поддержки в виде крылатой ракеты будет доделана(скорее ЕСЛИ она будет доделана(опять таки могу попробовать этим заняться)) чтобы ракета не спавнилась в воздухе она будет выстреливаться из установки на дестроере.
Также чтобы поддержка с воздуха не спавнилась посреди ничего, а над авианосцем(хотя бы).
Ну и для разнообразия просто напросто

### Alternative solutions

нет

### Additional context

Я конечно не знаю как создаются карты под antistasi. Но если ты считаешь что это неплохие идеи то я могу попробовать сам обновить карты , а ты даш фидбэк где что подправить

**Comment by igorkis-scrts** [comment]
Вертолётные базы там появились не от хорошей жизни и живут в основном на картах, где есть недостаток "сложных" точек для захвата вроде Ливонии. У меня эту цель выполняют military base'ы.

По поводу ракет и кораблей - проблема в том, что игроку от того, что ракета прилетела от физически существующего в игровом мире корабля ни холодно, ни жарко, игрок этого не видит.  Он может слетать туда разок из спортивного интереса, дабы удовлетворить своё любопытство, однако на этом ведь всё. Помимо производительности миссии, этот код надо написать и оттестировать, а это время и силы.

Аналогично и с поддержкой, спавнящейся в воздухе  - сидящий на точке игрок не знает, что поддержка спавнится из воздуха, он видит только то, как она прилетает и для него это, в общем-то, достаточно. То, что она спавнится в воздухе в коридоре или на авиабазе знает лишь админ или разработчик. По такой же логике можно убрать деспавн юнитов на расстоянии от игрока, потому что иначе игрок узнает что все аутпосты на самом деле не заселены и пока игрок не рядом, там никого нет.

**Comment by wersal454** [comment]
Понял Понял. По поводу кораблей ок согласен. А вот по поводу баз, может для разнообразия этих самых баз добавить чисто вертолётные базы которые будут классифицироваться как military base? И как они вообще создаются? Через редактор карт или через код ? Интересно просто

**Comment by igorkis-scrts** [comment]
> И как они вообще создаются? Через редактор карт или через код ? Интересно просто
Маркеры расставляются в 3DEN'е (редакторе карт), они затем парсятся миссией при инициализации. 
Есть powershell-сценарий в корне репозитория, можешь запустить его с флагом `Altis` и открыть миссию в редакторе, дабы посмотреть как это выглядит.
