### ISSUE TITLE
[Bug]: Транспортные самолёты очень долго не пропадают после вызова поддержки

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#165]
### Describe the bug

Транспортные самолёты очень долго не пропадают после вызова поддержки ну и лёгкие ударные вертолёты

### How to reproduce

вызвать поддержу

### Version

2.2.4

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted

### Additional context

![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/8110f08e-f700-4b36-a722-309b638bd856)
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/779294dc-eb5e-42ee-8867-fc143c065eef)

**Comment by wersal454** [comment]
А еще транспортные самолёты не высаживают(сбрасывают) десант (заметил после того как сбил их)
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/74466102-604d-45ce-85f8-ed6ec860bf1b)

**Comment by igorkis-scrts** [comment]
Самолёты сбрасывают также и только пехоту, тестировал вчера этот код. Просто происходит это не сказать что часто, у вертолётов обычно больше вес в массиве с вероятностями выбора техники для подкрепления.
Что делать с зависающими в воздухе, если честно, не знаю, так далеко я не копал. Если нет ошибок в .rpt-логе, то вообще сложно сказать почему так.
