### ISSUE TITLE
[Change Request]: Блокпосты

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#168]
### Is the requested change related to a problem?

нет

### Describe the solution you'd like.

Заметил что на блокпостах спавнятся ТОЛЬКО offroadы с пулемётами, ничего другого. Я так подозреваю это как-то связано с использованием в функции только milita'овской техники(я давно заглядывал конкретно в эту функцию возможно не совсем так). Вообщем было бы неплохо добавить и MRAPы и бтры на соответствующих уровнях войны.

### Alternative solutions

no

### Additional context

Возможно стоило создать БАГ issue, потому что вроде как в фунции бтры и прочее прописаны, но они не спавнятся 
Играл когда заметил такую штуку с arid NATO и CSAT. Пробовал с aegis поиграть там спавнились mrapы(потому что они видимо прописаны в теплейте как militialightvehicles вместо offroadов)

**Comment by igorkis-scrts** [comment]
```sqf
private _typeVehX = if (random 10 < (tierWar + (difficultyCoef / 2)) && {[_markerX] call A3A_fnc_isFrontline}) then {
			private _apcs = _faction get "vehiclesMilitiaAPCs";
			if (_apcs isEqualTo []) then {
				selectRandom (_faction get "vehiclesMilitiaLightArmed");
			} else {
				selectRandom _apcs;
			};
		} else {
			selectRandom (_faction get "vehiclesMilitiaLightArmed");
		};
```
Они спавнятся при высоком вар левеле на фронтлайн-точках, в основном.

**Comment by wersal454** [comment]
@igorkis-scrts 
Это ты поменял в патче? Просто честно честно у ванильных фракций по среди дороги всегда стояли только offroadы

**Comment by igorkis-scrts** [comment]
Нет, это довольно  старый код. Просто условия появления лёгкого БТР на дороге, как видишь, делают его довольно редким гостем в игре. Обычно он часто встречается в пограничных точках на 3-4-5 вар левеле.
