### ISSUE TITLE
[Bug]: Артиллерия NATO 

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#169]
### Describe the bug

Не вызывается артиллерия у NATO arid (возможно и у остальных). 

### How to reproduce

пропиши команду 
["ARTILLERY", Occupants, attack, 10000, player, getPosATL player, 1, 0] spawn A3A_fnc_createSupport;
и замени на Invaders чтобы убедится

### Version

2.2.4

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted

**Comment by wersal454** [comment]
Можно ли артиллерии прописать использование разных боеприпасов(хотя бы кластерных у 155 и ракетной) в magazines? Или код не позволит?

**Comment by wersal454** [comment]
Я поменяю при дебаге на кавычки. Странно что у захватчиков нормально вызывались.

"Можно, однако в 2.2.4 работать не будет, так как по дефолту выбирается первый элемент массива боеприпасов ("magazines") из темплейта. Я поправил на рандом в 2.3."
Напиши мне о добавлении в PR я тогда закину разные боеприпасы(подозреваю что наводящиеся боеприпасы работать врятли будут)

**Comment by igorkis-scrts** [comment]
Можешь закидывать, в следующую версию это гарантированно войдёт. Сейчас подолью код в бранч.
