### ISSUE TITLE
Cannot use Commander actions after Temp AI Control

### ISSUE THREAD

**Issue by Slendermang** [igorkis-scrts/A3-Antistasi-Plus#17]
After taking temp AI control of a high command squad, you can no longer access the commander options in the "Y" Menu. 
It will tell  you in a tooltip that you need to be a group leader in order to access this option.

**To Reproduce**
Take over a HC squad via temp ai control
Relinquish control
Attempt to use commander options on a HC squad

**Expected behaviour**
Be able to use commander controls on HC squads after using temp AI control

**Screenshots**

**Environment (please complete the following information):**
Version: 
Map (specify if Altis Blufor):  Antistasi Plus - Chernarus 2020

* [ ] LAN Hosted
* [ ] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
ACE3 with old medical
ACEX
CBA
CUP Terrains, Map & Map 2.0
CUP ACE3 Compatibility Addon - Terrains
RHS (GREF, USAF, RHAF)
RHS Ace Compat (GREF, USAF, RHAF)
Advanced Sling Loading
Enhanced Movement
Head Range Plus
JSRS
JSRS RHS (AFRF, GREF, USAF)
Loot to vehicle for Antistasi and ACE
No More Aircraft Bouncing

    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 
January 17th, 2021, 5PM EST
**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
[dump.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/5826986/dump.txt)

**Comment by igorkis-scrts** [comment]
Logs are empty due to `-nologs` flag.

**Comment by igorkis-scrts** [comment]
Marking this as obsolete as no logs were provided.
