### ISSUE TITLE
[Feature Request]: Q&A

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#177]
### Related problem

Хочу задать несколько вопросов по прошлым issue. Просто ты не на все вопросы ответил, а мне очень уж интересно.

### Proposed feature

1. По поводу маскхалатов и костюмов гили. Ты сказал что хотел бы сделать функцию патрульных снайперов, может мне тогда пока сделать категории "sniUniforms" в темпелейтах? Ты ещё сказал что не хочешь чтобы все снайпера были в костюмах, может я тогда militia оставлю в обычной униформе, military выдам гили , а элиткам выдам маскхалаты? И опять таки есть же категория споттер и отдельно снайпер, я и туда закину и туда.

2. Вопрос связанный с обновлением карт. Про корабли я понял что не имеет смысла, а вот вертолётные базы ты точно не хочешь добавить? Хотя бы в количестве одной штуки на карту(Мальден и карта из WS). Как ребята из CV объясняли , это сделано ещё и потому что к середине игры желательно чтобы у всех фракций была хотя бы одна авиабаза(в CV вертолётные базы считаются авиабазами)

2.5 Ты говорил что посмотришь ещё на спавн транспортных самолётов на аэродромах. У тебя получилось что-нибудь?

3. Функция sam и радара. Ты говорил что можешь доделать функцию радара для спавна не только стационарок(вроде как то так). Я попробал заспавнить скаут AAF и он нормально заработал даже без твоего хотфикса(смотреть issue связанный с SAM). Может стоит его закинуть? напомню радар на 8 км и на 360 градусов!

3.5 И без заполненного SAM в темплейте, радар не спавнится, так и задумано?

4.Очень не хватает обновления магазина на высоких уровнях войны(7-10). Мы это тоже уже обсуждали, но ты ничего и не ответил. В магазине не должна продаваться суперсовременная(мощная) техника. Просто по стандартам 2035 года техника AAF не такая уж и современная(или мощная) поэтому все оставшиеся LT можно было бы и добавить. И да суть игры в том чтобы игроки технику ЗАХВАТЫВАЛИ , но на маленьких картах к примеру(тот же мальден) негде взять самолёты после захвата одного из двух аэродромов, поэтому самолёт AAF дрыщавый мог там пригодится. LTшки тоже вообще ни разу не мощная техника, но всё же с пушками поэтому можно было бы и добавить для покупки на 7-8 лвлах когда нужно хоть какую-то технику надо купить. Ну и танк AAF собственно на 9-10 уровни закинуть , когда всё что остаётся это добить остатки врагов(с учётом денег которые игроки получают под конец карты это очень даже логично, этакий money sink).

4.5 Ещё можно было бы сделать проверку на прокачанность скилла армии для баланса. При уровне 15-20 бтр, 20-25 можно покупать LT и ударный лёгкий верт , а при 25-30 уже основной танк и истребитель нищенский (может ещё какие то варианты техники легкий вертолёт AAF к примеру или их транспортник)

5. Обновление магазина , но уже в плане экипировки. Я писал про добавление в магаз формы AAF(и возможно LDF), но ты на это не ответил. Эти униформы и так можно снять с трупов(да да стянуть не равно купить, надо заслужить), но суть не в этом(униформу нато и csat можно стянуть с ace'ом) просто мне кажется раз уж AAF нищенские значит и всё их снаряжение "общедоступное" почему бы ему не оказаться у торговца? Черный спортивный костюм так уж точно можно добавить.

5.5. А ещё броники и прочие атрибуты. Есть одни вариации(камуфляжи к примеру) ,а других нет. Тоже не совсем понимаю. Есть ещё хим маски, но хим костюмов нет. И черный спортивный костюм и одежда наёмников.

6. Расширение пула десантируемой техники. Есть новости ? https://github.com/igorkis-scrts/A3-Antistasi-Plus/issues/156#:~:text=%D0%92%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%2C%20%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C%20%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F,%D0%B1%D1%8B%D0%BB%D0%BE%20%D1%81%D0%BB%D0%B8%D1%88%D0%BA%D0%BE%D0%BC%20%D0%BB%D0%B5%D0%B3%D0%BA%D0%BE.

7. Бронированные пикапы. Ты закинул их только в темплейт повстанцев, так ведь? А я думал закинуть к militia во все ванильные темплейты. Может мне этим заняться? 

8. Я видел ты добавил в initsupport UAV. А функция рабочая? Планируешь ли ты дорабатывать крылатую ракеты и ганшип?

### Additional context

Пожалуйста ответь на все вопросы поподробнее, чтобы я потом не уточнял лишний раз.

**Comment by wersal454** [comment]
Ну и дай отмашку чтобы я добавил что-нибудь(что смогу)

**Comment by igorkis-scrts** [comment]
1. Я ещё думаю над тем, как это лучше сделать. Скорее всего, всё придёт к тому, что будет использована группа `groupSpecOpsSniper` (которая сейчас не используется) и в ней будут отдельные типы юнитов `GhillieSniper` и `GhillieSpotter`, и спавниться они будут только в контрол-зонах.
2. С Малдена вертолётная база была удалена по двум причинам - она была довольно уродливо сделана (это вроде была стандартная композиция из габионов и зеленых карго-домиков) и потому что на Малдене довольно тесно. Да, идея о том, что у каждой фракции должна быть авиабаза, звучит разумно, да а против конкретно вертолётных баз ничего против не имею, однако, просто накиданные в поле объекты выглядят на мой вкус невероятно уродливо и я стараюсь обходиться без них где возможно.
![20230821231450_1](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/6746043/42cbe8e5-c3c5-4aba-a6c5-7ddea829d812)
2.5. Функция работает, однако, далеко не во всех случаях, это, вероятно, связано с тем что маркер авиабазы может находиться довольно далеко от ВПП, а также то что ВПП не на всех картах хорошо сконфигурированы. В целом, это можно было бы сделать, но мне кажется это довольно незначительным, поэтому я не стану этим заниматься.
3. Вообще, я посмотрел код, действительно он работает и для пилотируемой техники и эту машинку можно использовать, однако, всё ещё не очень понятно что выставлять AAF'у в пару, SAMы в игровом коде работают в паре ЗРК-радар. Разве что ставить рядом там вторую маленькую зенитку, но она вроде уже и так катается там.
4. Да, это проблема ванилки, магазин техники вообще создавался с RHS/3CB Factions  в уме, где ассетов много и на любой вкус. А так я тогда ответил - я говорил что не хочу продавать крутую и современную технику, это идёт вразрез с геймплейной петлёй игры о ребелах, противоречит игровой экономике и механике. 🙃 В RHS-темплейтах, например, игроки не могут купить ничего круче каких-нибудь Т-55, турбовинтового супертукано - в общем, принцип такой, что танк, например, купить можно, но плохонький и ни в коем случае не Т-90 или Абрамс в полном обвесе. В ванилке такой сет собрать невозможно ввиду недостатка ассетов, а *Лепик* не сильно-то и хуже Сламмера или Т-100. Маленькие тачанки AAF, впрочем, забросить можно.
4.5 У этой идеи не хватает "физикальности", реального присутствия в игровом мире. Например, если захвачен морской порт и открываются новые виды техники в магазине, можно додумать что технику на черный рынок теперь могут возить морем, что означает что качество и география поставок улучшились. Скилл ребелов - это абстрактная цифра, игрок не может её "увидеть" в игровом мире, только посмотреть в меню командира, поэтому я бы не стал привязывать какую-либо прогрессию магазина к ней.
5. Формы AAF и LDF можно стянуть потому что они технически принадлежат зеленым-индепендентам, что является техническим ограничением. А так униформы, я бы сказал, слишком незначительны чтобы продавать их в магазине - они влияют, по большому счету, лишь на внешний вид (кроме костюмов КСАТ), а все vanity-вещи лучше добавлять сразу в темплейты ребелов. Вообще, я вижу повторяющуюся идею о том, чтобы слепить из ребелов AAF посредством выдачи и продажи им их всего снаряжения, но я думаю что это противоречит основной идее игрового режима как симулятора герильи, инсургентов и так далее.
6. Я потестировал код с техникой без пассажиров и мне он не сказать что понравился - техника после приземления сразу срывается с места и уничтожается, пехота где-то плетется где-то сзади и приходит, когда приданную им технику уже давно сожгли, я всё же хотел чтобы они действовали как одна тактическая единица в одном порядке. Также вспомнил, почему я не сажу сразу десант в технику до десантирования - потому что во многих модах есть пассажирские места на броне вместо салона, и сидящие солдаты на броне в полёте выглядят невероятно комично. Починить это нет возможности, потому что нет реальной возможности различить находится пассажирское место в салоне или снаружи.
7. Для военных мне они показались, все же, несколько кустарными, поэтому я не стал их добавлять. Плюс одинаковость ассетов - должно же быть у ребелов что-то уникальное.
8. Рабочая, однако, бесполезная, понимаю, почему Комьюнити её выключили - UAV просто летает над вами и спотает, больше ничего не делает. Не знаю, включать ли её в итоге, просто "чтобы было" - ну такое. Cruisemissile - я как-то разговаривал с комьюнити по её поводу полгода-год назад, там что-то было сломано, вроде как.  Gunship - не тестировал, поэтому не знаю.

> Пожалуйста ответь на все вопросы поподробнее, чтобы я потом не уточнял лишний раз.
Дружище, ну я же не чатГПТ, отвечаю как могу. 🙃 

Вообще, на самом деле, многие идеи у тебя неплохие сами по себе, однако они не подходят к тому, каким я вижу Плюс. Я так полагаю, ты играешь с друзьями и есть вещи, которые вам не нравятся и вы хотели бы изменить. Это вполне нормально. Я думаю, что завести свой форк и делать вещи на свой вкус - хорошая идея, собственно, я так и поступил в своё время, и это, несомненно, более продуктивно чем спорить со мной о вкусах и доказывать мне как я неправ. Я очень даже могу быть неправ, однако, именно поэтому я и отселился в свой отдельный форк Antistasi Plus.

**Comment by wersal454** [comment]
"Дружище, ну я же не чатГПТ, отвечаю как могу. 🙃

Вообще, на самом деле, многие идеи у тебя неплохие сами по себе, однако они не подходят к тому, каким я вижу Плюс. Я так полагаю, ты играешь с друзьями и есть вещи, которые вам не нравятся и вы хотели бы изменить. Это вполне нормально. Я думаю, что завести свой форк и делать вещи на свой вкус - хорошая идея, собственно, я так и поступил в своё время, и это, несомненно, более продуктивно чем спорить со мной о вкусах и доказывать мне как я неправ. Я очень даже могу быть неправ, однако, именно поэтому я и отселился в свой отдельный форк."

Да сорянба. 
Отделятся в отдельную форку я не хочу(и не могу). Да и играю я один. Начал в одиночку, 2 месяца проиграл, а там ребята подтянулись пока в таркове вайп ждали.

Спасибо что на всё ответил(не на всё, пункт 5.5) , но последние два момент.
7.  "все же, несколько кустарными, поэтому я не стал их добавлять" а обычные пикапы с пулемётами, это не кустарно) Ну конечно чуть менее кустарно , но всё же
8. Может тогда добавить UAV возможность стрелять? + плюс в моём PR к ним вроде кто-то проговорился о том что необходимо убедится что дроны в плане вооружения совместимы, так что может они всё таки должны ещё и оружие использовать. "просто "чтобы было" - ну такое" у меня есть идея по этому поводу.

Напиши по поводу 5.5!

3."Разве что ставить рядом там вторую маленькую зенитку, но она вроде уже и так катается там." Ну кстати почему бы и нет учитывая что зенитки и sam всегда на базе спавнятся и выполняют одну и туже роль по сути.
4."Маленькие тачанки AAF, впрочем, забросить можно."

Пунктами 3 и 4 мне заняться? Я могу.

**Comment by igorkis-scrts** [comment]
> Отделятся в отдельную форку я не хочу(и не могу). 

Ну, тогда тебе придётся неизбежно принять тот факт, что некоторые пулл-реквесты и предложения могут быть завернуты с пространными объяснениями и/или формулировкой "мне кажется, что это не очень подходит к проекту". Я не против contributions в проект, однако, как основной мейнтейнер, я веду постоянный триаж по поводу того, что нужно проекту, а что нет, плюс мое время довольно ограничено и надо постоянно решать, чем стоит заняться, а чем нет.

> а обычные пикапы с пулемётами, это не кустарно)

Это, опять же, не от хорошей жизни - у ванилки критический недостаток ассетов.

> Может тогда добавить UAV возможность стрелять?

Это здравое предложение, но кто-то этот код должен написать и оттестировать во всех возможных окружениях и конфигурациях.

> 5.5. А ещё броники и прочие атрибуты. Есть одни вариации(камуфляжи к примеру) ,а других нет. Тоже не совсем понимаю. Есть ещё хим маски, но хим костюмов нет. И черный спортивный костюм и одежда наёмников.

Противогазы нужны как защита от CHEMICAL-саппорта. Остальное, по большому счету, остатки из кастомной сборки, в которую мы игралс с комьюнити, на которые ранее никто не обращал внимания (абибас-горку и гилли-костюмы попросили друзья). В целом, проблема в том, что черный спортивный костюм - это вроде как Горка с хорошими значениями брони, а это значит что её в итоге, в конечном итоге, будут носить вообще все включая ботов (заметил тенденцию, что командиры стараются одеть ботов в самую лучшую броню, чтобы улучшить выживаемость на аутпостах). Про костюмы я уже писал в прошлом сообщении.

> Пунктами 3 и 4 мне заняться? Я могу.
Вообще - можно.

**Comment by wersal454** [comment]
Ок. как я уже писал. Твой мод твоё право, безусловно, моя работа предлагать)

Ответь под последним принятым PRом, я там написал про минные снаряды. И PR про гражданские вертолёты там вопрос есть.

А и BUG issue тоже оставил перед этим постом.

Спасибо!
