### ISSUE TITLE
[Change Request]: Можешь объяснить почему variants не работают в гражданских темплейтах?

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#182]
### Is the requested change related to a problem?

Я попробовал добавить строчки variants и animation в дефолт темплейты(как они работают кстати?), но не помогло.
![image](https://github.com/igorkis-scrts/A3-Antistasi-Plus/assets/29953387/226c4aff-8956-4d4e-b63c-9d619f9e573b)

### Describe the solution you'd like.

Если объяснишь в каких файлах нужно что прописать, чтобы variants заработало я был бы признателен.

### Alternative solutions

.

### Additional context

.

**Comment by igorkis-scrts** [comment]
Код не поддерживает варианты у цивилианов, так как не было нужды это делать. Я добавил в будущую версию их проброс.

**Comment by wersal454** [comment]
Ага! Теперь то я понимаю что за файл мне надо было найти! Спасибо
