### ISSUE TITLE
[Feature Request]: Уже апдейт???

### ISSUE THREAD

**Issue by wersal454** [igorkis-scrts/A3-Antistasi-Plus#187]
### Related problem

ПОГОДИ ПОГОДИ.

### Proposed feature

У меня ещё осталась ещё одна(как всегда не шибко полезная) фича , помимо обновления черного рынка!!!

### Alternative solutions

.

### Additional context

.

**Comment by wersal454** [comment]
Черт ,чутка не успел

**Comment by igorkis-scrts** [comment]
Да, всё, апдейт выщел. Признаться честно, я его вообще не планировал делать так как я завершил разработку Плюса ещё в марте 2023 года и выкатился из Армы 3 как таковой, но так получилось что комьюнити-версию было легко портануть на Плюс, поэтому я решил немного ещё подзадержаться. 
Апдейтов больше не будет кроме хотфиксов критических багов уровня "мод сломался совсем".

**Comment by wersal454** [comment]
Ой да ну. Я смотрю у тебя отдельная ветка с ганшипом есть. Ты её вот так бросишь ?

**Comment by igorkis-scrts** [comment]
С ганшипом всё не так просто - код работы саппорта из пре-3.0-версии комьюнити, который несовместим с тем, как саппорты работают сейчас. В общем, надо долго мудохаться чтобы заставить его работать.

**Comment by wersal454** [comment]
Эххх... ну ладно. Чекни хоть напоследок мой последний PR. Там и смотреть особо нечего так-то. Ну и было весело собственно говоря, делать 5тыщмильонов веток и PR'ов. Пойду докучать ребятам из ultimate. 👍
