### ISSUE TITLE
(CUP) Rocket Technicals are too powerful, and too cheap.

### ISSUE THREAD

**Issue by SpadesNeil** [igorkis-scrts/A3-Antistasi-Plus#19]
**What, in your opinion, is currently wrong with the balance?**
I have this one guy on my server who does nothing but spam rocket technicals at objectives. It makes things really not fun for everyone else because he just launches a barrage of rockets at a target over and over again. I had to tell him to stop doing it under the excuse that he was blowing up arsenal crates we could have salvaged. No idea if this is actually true. Someone complained about this so I assume it's true. Accuracy is very poor with these rockets but that doesn't matter when he fires hundreds and hundreds of rockets, usually flattening an entire area before he's satisfied. They most often use the vehicle arsenal to rearm, an ammo truck if they have one because it offers an infinite resupply, or failing either of those they just keep shoving the artillery back into the garage and pull it out again completely rearmed. They can also just buy more of them because they're so cheap. I find rocket technicals just randomly abandoned all over the place. It's absurd.

**Describe the solution you'd like**
- Make rocket technicals _much_ more expensive than they currently are. Like, it should equal the cost of a tank at least. This is probably the easiest way to mitigate the problem, but doesn't solve it completely.
- This is more complicated, but using artillery attacks frequently could cause the AI to deploy air-based protection to find and destroy player artillery. No, I don't mean those awful air strikes from old Antistasi that pinpoint exactly where you are the moment you sit still for too long. I mean like a helicopter or a jet that gets sent on a search and destroy objective in your vicinity, that you would have time to notice and either counter it or try to run away before it blasts you. Either way, some kind of mechanic that makes the AI _look_ for you, and upon finding you, either shells you in response or sends an air strike or attack helicopter. I think an attack helicopter is the best solution.
- Add a cooldown (or a larger cooldown?) on vehicles being taken in and out of the garage.

**Describe alternatives you've considered**
- A config option to remove artillery technicals from Antistasi Plus.
- Remove artillery technicals entirely from all versions of the game.
- Replace rocket artillery technicals with some kind of mortar technical, if such a thing exists. Not sure it does in CUP. I know mortar vehicles exist in other contexts but I've never seen them.

**Additional context**
These events were witnessed on a port of Antistasi Plus to the map Tavania during a campaign about a month ago. If these issues are not relevant anymore, just close this.

**Comment by igorkis-scrts** [comment]
It looks like that you guys are still playing on **1.4** _(i guess because it is the only version where CUP somewhat works together with RHS)_.
Hilux with UB-32 pod was replaced by Hilux with Podnos mortar in **1.4.1**:
https://github.com/igorkis-scrts/A3-Antistasi-Plus/releases/tag/v1.4.1

**Comment by SpadesNeil** [comment]
Well, we weren't using RHS, that's for sure. The rocket Hilux is CUP.

But yeah, the timeline of this patch's release coincides with the time we were running the server. I'll try to make sure I only report more up-to-date stuff from now on.
