### ISSUE TITLE
If Petros dies while no commander is online, you soft-lock the campaign.

### ISSUE THREAD

**Issue by SpadesNeil** [igorkis-scrts/A3-Antistasi-Plus#21]
**Describe the bug**
If Petros is killed while no players are currently set as commander, the game is unable to generate a new base, and therefore Petros never respawns. This prevents further progress in the campaign because Petros is dead and all of the assets at the base are lost including the arsenal and vehicle crates.

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant):
- Have current commanders resign or leave.
- While the game indicates there is no commander, Petros is killed.
- Above issue occurs.

**Expected behaviour**
For the game to immediately ask to move the base when the next commander is chosen.

**Screenshots**
N/A

**Environment (please complete the following information):**
Version: 1.4.2 Napf https://steamcommunity.com/sharedfiles/filedetails/?id=2309970401

* [ ] LAN Hosted
* [x] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
https://cdn.discordapp.com/attachments/658769176684527627/802951807797559336/Antistasi_Plus_Napf_V2_JSRS.html
    
Time the bug occurred (Please leave in GMT+0):
Approximately 10:00AM (GMT-5)

**Additional context**
Restarting the server revives Petros.

Unable to obtain .RPT file at this time as serverbox is temporarily inaccessible. If this is super necessary I will grab it later, I just had to post this before I forgot about it again.

**Comment by igorkis-scrts** [comment]
Can't reproduce this on 1.6 and unstable 1.7. Will reopen if bug still persists.
