### ISSUE TITLE
Emplacement static weapons BUG

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#28]
**Describe the bug**

when static weapons  crew get kill no one Replace static weapons  even reset check point (move far to despawn and come back or restart mission) check garrison unit static is gone but static weapons still spawn with no crew

**To Reproduce**
Steps to reproduce the bug (If you can't reproduce it, just give details of what happened beforehand. Anything you think could be relevant): 

static weapons  crew dead

**Expected behaviour**

static man Replace when static crew is dead at least when reset check point

**Screenshots**

**Environment (please complete the following information):**
Version: 1.4.2
Map (specify if Altis Blufor): Altis 

* [*] LAN Hosted
* [ ] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset : CUP
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by igorkis-scrts** [comment]
Fixed in 1.5.2.
