### ISSUE TITLE
HQ gets stuck at default location, arsenal unusable (Dedicated Server)

### ISSUE THREAD

**Issue by sinat50** [igorkis-scrts/A3-Antistasi-Plus#29]
**Describe the bug**
HQ doesn't seem to be responsive on a dedicated server. When selecting where to place the HQ on mission startup, Petros and all the HQ resources stay in the default location even if you place it across the map. The map will show your HQ as being in the new starting location and you will spawn there, but Petros and the rest of the stuff don't move. The arsenal gets especially glitched where trying to access it gets you stuck in the loading screen.

**To Reproduce**
Setup a dedicated server with Antistasi Plus. Pick an HQ anywhere except the default location, or even a small distance away from it. Upon spawning the map will show you as in your HQ but Petros and the rest of HQ remain at the default. A switch over to spectator camera will let you see this. I have recreated it in the Altis and Chenarus maps. With or without mods the problem persists. Vanilla Antistasi Community editions seem to still work. Hosting over internet on my PC allows me to play with my friends no problem but the dedicated server I'm renting seems to be stuck with it.

**Expected behaviour**
HQ should move to wherever I choose on mission start. Arsenal should experience a short loading screen the first time you access that session.

**Environment (please complete the following information):**
Version: 1.5.1
Map (specify if Altis Blufor): Altis, Chenarus

* [ ] LAN Hosted
* [ X] Private dedicated server
* [ ] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset: RHS, 3CB, ACE (no medical) // Issue is unrelated to mods as it still occurs with mods disabled.
    
Time the bug occurred (Please leave in GMT+0): Has been occuring since I started the server 3 days ago.
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: Pacific Daylight Time (GMT -7)

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.
[arma3server_x64_2021-05-14_23-07-58.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/6484195/arma3server_x64_2021-05-14_23-07-58.txt)

**Comment by sinat50** [comment]
Attempting to select the Move HQ option will put Petros into a combat aware state like he wants to move, but he doesn't join the unit or move. After a short delay he will give the option to build HQ which does nothing but return him to his passive state.

**Comment by sinat50** [comment]
Bug also recreated in 1.5.2 Altis

**Comment by igorkis-scrts** [comment]
Case closed with the headless client usage.
