### ISSUE TITLE
Typo on WL required for training FIA troops

### ISSUE THREAD

**Issue by Partexedd** [igorkis-scrts/A3-Antistasi-Plus#32]
**Describe the bug**
There are typos on the War Level requirements for training troops, it displays the double of the current WL

**To Reproduce**
Check the requirement text after trying to train the troops

**Expected behaviour**
The requirement text should display the next WL

**Screenshots**
![image](https://user-images.githubusercontent.com/48566841/119120856-0ed3fa80-ba2d-11eb-925c-e53d76a6d4f7.png)

**Comment by igorkis-scrts** [comment]
WL requirement will be removed in 1.5.4, thanks for the report.

**Comment by igorkis-scrts** [comment]
Fixed in 1.5.4.
