### ISSUE TITLE
Unable to sell vehicles

### ISSUE THREAD

**Issue by Partexedd** [igorkis-scrts/A3-Antistasi-Plus#33]
**Describe the bug**
Vehicles can't be sold inside the HQ range until a server restart if the commander first tries selling them outside its range

**To Reproduce**
First try selling a vehicle outside the range of the HQ flag then try selling it inside its range, you'll get a message stating "Vehicle sale already in progress." but you won't be able to sell it until the server restarts

**Expected behaviour**
You should be able to sell it as soon as it enters the HQ range

**Screenshots**
Not a screenshot but should leave the bug report clearer
https://streamable.com/z2h5h7

**Comment by igorkis-scrts** [comment]
Thanks for the report! Found the source of issue, will be fixed in 1.5.4.

**Comment by igorkis-scrts** [comment]
Fixed in 1.5.4.
