### ISSUE TITLE
A parameter to modify the starting gear on enemy factions

### ISSUE THREAD

**Issue by Partexedd** [igorkis-scrts/A3-Antistasi-Plus#35]
**Is your feature request related to a problem? Please describe.**
Not really related to any problem but would be cool if you could set a parameter to start against tier 2 or tier 3 troops

**Describe the solution you'd like**
If possible a parameter to change the starting gear for both factions so they start better armed on all garrisons adding that extra difficulty

**Describe alternatives you've considered**
Replace the T1 troops on garrisons or reinforce them with better armed troops (depending on WL) while maintaining the original T1 troops

**Additional context**

**Comment by igorkis-scrts** [comment]
There will be a mechanism that will allow higher tier infantry to appear due to high aggro, but no parameter - too complicated to implement.
