### ISSUE TITLE
SHIFT+Y menu non functional

### ISSUE THREAD

**Issue by LemonXVI** [igorkis-scrts/A3-Antistasi-Plus#37]
The menu for using artillery units in high command does not appear when pressing the SHIFT+Y hotkey.

Version: 1.5.4.1
Map: Taviana

* [ x] Private dedicated server

Modset: RHS+3CB+ACE+TFAR

**Comment by igorkis-scrts** [comment]
This menu was moved to AI Management submenu button due to keybinding conflict with Zeus.
