### ISSUE TITLE
Enemy AT static spawn on top tower

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#38]
**Is your feature request related to a problem? Please describe.**
Enemy AT static spawn on top tower is useless they can't fire .

**Describe the solution you'd like**
change position to some locate that can fire or just remove it .

**Describe alternatives you've considered**
if possible spawn platform under AT static .

**Comment by igorkis-scrts** [comment]
Changed in 1.6.
