### ISSUE TITLE
Can't order to create minefield when explosive is Unlock

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#39]
**Describe the bug**
Can't order to create minefield when explosive is Unlock

**To Reproduce**
unlock explosive

**Expected behaviour**
Can order to create minefield when explosive is Unlock

**Environment (please complete the following information):**
Version:  1.5.4.1

* [ ] LAN Hosted

Modset:
RHS

**Additional context**
explosive checker is only check they are more then 5 or not but unlocked number is -1 .

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by igorkis-scrts** [comment]
Infinite explosives have been removed from Antistasi Plus.
