### ISSUE TITLE
disable Log when Lan host that show load unit

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#40]
**Is your feature request related to a problem? Please describe.**
too much text 

**Describe the solution you'd like**
disable Log 

**Additional context**
![20210530204752_1](https://user-images.githubusercontent.com/23005914/120106863-e82e6600-c188-11eb-8c6d-f648457651ff.jpg)

**Comment by igorkis-scrts** [comment]
Fixed in 1.5.5.
