### ISSUE TITLE
Gov unit spawn at Inv base

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#42]
**Describe the bug**
Gov unit spawn at Inv base at specifically location , old version of mission they shoot each other but this version Gov unit is opfor side

**To Reproduce**
Inv capture military base

**Expected behaviour**
not mix Unit .

**Screenshots**
![20210531164549_1](https://user-images.githubusercontent.com/23005914/120175937-ea4bff80-c230-11eb-92a2-0cd79cf3209b.jpg)
![20210531164558_1](https://user-images.githubusercontent.com/23005914/120175943-eb7d2c80-c230-11eb-878d-7ced98b43076.jpg)
![20210531164614_1](https://user-images.githubusercontent.com/23005914/120175944-ec15c300-c230-11eb-9622-db5976931ea2.jpg)

**Environment (please complete the following information):**
Version: 1.5.5

* [ ] LAN Hosted

Modset:RHS

**Comment by igorkis-scrts** [comment]
Thanks for report, i will take a look.

**Comment by igorkis-scrts** [comment]
Somewhat fixed in 1.6.
