### ISSUE TITLE
RHS used Rocket launcher unlock able!

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#43]
**Describe the bug**
used Rocket launcher they can't fire 

**To Reproduce**
collect used Rocket launcher for unlock

**Expected behaviour**
can't not unlock or add used Rocket launcher to arsenal, 
if possible make loot box not add used Rocket launcher  in the box

**Environment (please complete the following information):**
Version: 1.5.5
Map: altis

* [ ] LAN Hosted

Modset:RHS

**Comment by igorkis-scrts** [comment]
Somewhat fixed in 1.6 (RHS empty launchers will be removed from arsenal on each arsenal tick).
