### ISSUE TITLE
More AI Command.

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#45]
**Is your feature request related to a problem? Please describe.**
i don't know there are issue or not it like make AI more useful sine they are main part of game play.

**Describe the solution you'd like**
1.add ability AI to get in friendly vehicle (transport) - rebel don't have much vehicle put it to good use
2.add ability AI to join group with player - some time  flag not available due enemy attack
 commander can sent reinforcement to friendly player or make good use AI that on AO not need to send back to HQ
3.add ability AI to leave player group and add to high command - some time spilt AI out to do some task if have this ability we can custom unit team and a lot of good use

**Comment by igorkis-scrts** [comment]
1 is already there - you can assign vehicle to AI squad.
3 will arrive with AP 1.7.
