### ISSUE TITLE
INV not Spawn in resource and factory

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#46]
**Describe the bug**
INV not Spawn in resource and factory

**To Reproduce**
INV  capture  resource and factory

**Expected behaviour**
INV spawn in resource and factory

**Environment (please complete the following information):**
Version: 1.5.5
Map: altis

* [ ] LAN Hosted

Modset:RHS

**Comment by igorkis-scrts** [comment]
Does not reproduce.
