### ISSUE TITLE
Reble AI shoot arm CIV at punishment mission

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#47]
**Describe the bug**
Reble AI shoot arm CIV at punish mission and lead mission fail.
but CIV not shoot back to reble.

**To Reproduce**
bring AI to  punishment mission

**Expected behaviour**
Reble AI not shoot arm CIV

**Environment (please complete the following information):**
Version: 1.5.5
Map: altis

* [ ] LAN Hosted

Modset:RHS

**Comment by igorkis-scrts** [comment]
Limitation of Arma - there are only 4 sides and there is no real way to make civilian side enemy to invader side except making them occupant side. As a side effect, they're hostile to player faction too.
There's nothing can be except Invader Mission removal.
