### ISSUE TITLE
AI control duration - high command

### ISSUE THREAD

**Issue by Trianglemang** [igorkis-scrts/A3-Antistasi-Plus#48]
**Describe the bug**
Scenario parameter for "AI Control Time Limit" does not apply to AI teams in high command.

**To Reproduce**
1. New save. 
2. Set parameter for AI control time to anything other than default.
3. Get a radio `["ItemRadio"] call A3A_fnc_unlockEquipment;`.
4. EITHER Recruit inf team OR Start watchpost.
5. Select team in high command.
6. "Remote control" team from antistasi menu.

**Expected behaviour**
Popup text should say something other than "Time to return control to AI: 60". Remote control should conttinue past 60s.

**Environment**
Version: 1.6 (on Steam Workshop - Updated: 12 Jun @ 5:35pm)
Map: Altis (or Tanoa or Livonia)
[X] LAN Hosted
Modset: no mods

**QoL request**
 Unrelated to the 'bug', but it'd be nice if you didn't lose control of your watchpost pair on a quadbike by injuring them driving down the tracks/trails on tanoa 😢. The small steps around the default start position are enough to trigger them.

**Comment by igorkis-scrts** [comment]
Already fixed in the upcoming AP 1.7.
