### ISSUE TITLE
[v1.7] Helicopter crash task outside of map - Weferlingen

### ISSUE THREAD

**Issue by TomMaverick** [igorkis-scrts/A3-Antistasi-Plus#51]
**Describe the bug**
The "Helicopter crash" task is spawning outside of the map boundaries when your base is close to the edge of the map.
I encountered this problem only on Weferlingen so far. I had my base at the following position and the downed helicopter already spawned at the positions marked with the red X in the screenshot below.
Of course I was not able to recover the helicopter because you cant go out of map for longer than 30? seconds.

**To Reproduce**
1.) Start at the location I started at.
2.) Try to get the helicopter crash mission. Sometimes it will spawn outside the map.

**Expected behavior**
Spawn the mission inside the map boundaries.

**Screenshots**
![image](https://user-images.githubusercontent.com/66076646/127017648-ec8bd907-dfd0-4230-bc8b-9d5e0289244f.png)

**Environment (please complete the following information):**
Version: 1.7 from 25. July
Map: Weferlingen
* [x ] Private dedicated server with Headless client(s)

**Modset:**
    - RHS + 3CB Factions  (Cold War mode)

**Here the part of the RPT log where the task loading happens.**
<details>
  <summary>RPT Log</summary>
  

17:46:23 2021-07-26 15:46:23:788 | Antistasi | Info | File: fn_scheduler | Scheduled function: A3A_fnc_LOG_Helicrash, Function params: ["control_65"]

17:46:23 2021-07-26 15:46:25:174 | Antistasi | Info | File: fn_LOG_Helicrash | Helicrash mission init. | Client: hc [5]

17:46:23 2021-07-26 15:46:25:196 | Antistasi | Info | File: LOG_Helicrash | Difficulty: false, Side: EAST, Destination: Forest near Hödingen | Client: hc [5]

17:46:23 2021-07-26 15:46:25:196 | Antistasi | Info | File: LOG_Helicrash | Pilot: loadouts_inv_other_Pilot, helicopter: UK3CB_CW_SOV_O_LATE_Mi8AMT, search heli: UK3CB_CW_SOV_O_LATE_Mi8, Box: B_supplyCrate_F, cargo truck: UK3CB_CW_SOV_O_LATE_Ural_Open, APC: UK3CB_ARD_O_GAZ_Vodnik_KVPT, infantry array: ["loadouts_inv_militia_SquadLeader","loadouts_inv_militia_LAT","loadouts_inv_militia_Rifleman","loadouts_inv_militia_MachineGunner","loadouts_inv_militia_Rifleman","loadouts_inv_militia_Engineer","loadouts_inv_militia_Radioman","loadouts_inv_militia_Medic"] | Client: hc [5]

17:46:23 2021-07-26 15:46:25:220 | Antistasi | Info | File: fn_LOG_Helicrash | Helicrash position has been found after 30 iterations. | Client: hc [5]

17:46:23 2021-07-26 15:46:25:220 | Antistasi | Info | File: fn_LOG_Helicrash | Helicrash position: [18610.7,5988.44,0] | Client: hc [5]

17:46:29 2021-07-26 15:46:30:382 | Antistasi | Info | File: LOG_Helicrash | Box type: "B_supplyCrate_F", box position: [18605.7,5983.13,-0.4478] | Client: hc [5]

  
</details>

**Comment by igorkis-scrts** [comment]
Fixed in the current build.
