### ISSUE TITLE
[v1.7] Rebel loadout - Uniform not saving

### ISSUE THREAD

**Issue by TomMaverick** [igorkis-scrts/A3-Antistasi-Plus#52]
**Describe the bug**
It seems like the uniform of rebels is not saved after editing it in the rebel loadout.
Helmet, Vest, Weapons and the rest seem to work.

There is nothing about it in the RPT log.

**To Reproduce**
1.) Save a loadout for a rebel
2.) Spawn a rebel at the flag
3.) Rebel not wearing the uniform you selected

**Expected behaviour**
Rebels wearing the correct uniform.

**Environment (please complete the following information):**
Version: 1.7 from 25. July
Map: Weferlingen
* [x ] Private dedicated server with Headless client(s)

**Modset:**
      - RHS + 3CB Factions  (Cold War mode)

**Comment by igorkis-scrts** [comment]
It is intended - i want to avoid clone troopers and differ them at least in uniforms.
Hint about this behavour is already there.
