### ISSUE TITLE
[v1.7] Destroy task seem to be bugged with radio towers - Weferlingen

### ISSUE THREAD

**Issue by TomMaverick** [igorkis-scrts/A3-Antistasi-Plus#53]
**Describe the bug**
I got a radio tower in 4000m radius that is not occupied by me. If I ask for a destroy task the game tells me that there must be an Airbase or Radio Tower in 4km radius.

Mission range is set to 4000m in the parameters.

There is nothing about it in the RPT log.

**To Reproduce**
1.) Start in an area with only a radio tower in the radius.
2.) Ask for a destroy mission
3.) No mission will be assigned and a message will show up that says: "Destroy Missions require Airbase or Tower closer than 4km from the HQ"

**Expected behaviour**
Mission should work.

**Screenshots**
Radio tower is under 1000m away
![image](https://user-images.githubusercontent.com/66076646/127036301-930b7d9e-9f6d-4bdf-abdf-5468546711db.png)

**Environment (please complete the following information):**
Version: 1.7 from 25. July
Map: Weferlingen
* [x ] Private dedicated server with Headless client(s)

**Modset:**
      - RHS + 3CB Factions  (Cold War mode)

**Comment by igorkis-scrts** [comment]
Thanks for report. 
At this point, only occupant radio towers might be picked for destroy task, i think this is design oversight inherited from community version.

**Comment by igorkis-scrts** [comment]
Fixed in the current unstable branch.
