### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by TheOfficialDroid** [igorkis-scrts/A3-Antistasi-Plus#54]
### Describe the bug

Rally points teleport to the wrong position, in our case; The middle of the ocean?

### How to reproduce

Placing down a rally point,

Seems to happen randomly and when you're not clicking directly on the RP marker.

### Version

1.7

### Have you altered the code?

No

### Map

Altis

### What server?

Private dedicated server

### Mods

```html
RHS, ACE, TFAR
```

**Comment by igorkis-scrts** [comment]
To be honest, seems to be more like network/server performance issue (getPos command returns [0,0,0] position which exactly the map corner).
Can't reproduce this behaviour.

Maybe .rpt logs will show something.

**Comment by TheOfficialDroid** [comment]
> To be honest, seems to be more like network/server performance issue (getPos command returns [0,0,0] position which exactly the map corner).
> Can't reproduce this behaviour.
> 
> Maybe .rpt logs will show something.

Haven't had a chance to test since; However the server is running on a brand-new OTB Dell PowerEdge EPYC server; Performance issues aren't a factor, network might be an issue.

Haven't encountered the issue since; Will keep an eye out and re-open if I can get a fully reproduceable occurrence of it.... 1.6 was working perfectly fine, 1.7 is where the issue occurred after updating.

**Comment by igorkis-scrts** [comment]
Well, you could reopen issue if it will happen again.

Rally Point code wasn't changed since 1.6 though.
