### ISSUE TITLE
[Bug]: Roadblock objects "Multiply"

### ISSUE THREAD

**Issue by TheOfficialDroid** [igorkis-scrts/A3-Antistasi-Plus#55]
### Describe the bug

Roadblock Emplacements duplicate their "block model" (junk pile) whenever players, leave and get close to them...

### How to reproduce

Move away from a roadblock then get within the distance you've set them to spawn in.

### Version

1.7

### Have you altered the code?

No

### Map

Altis

### What server?

Private dedicated server

### Time bug occured (Server time/UTC)

17/08/2021 - 16/08/2021

### Mods

```html
RHS, TFAR, ACE
```

**Comment by igorkis-scrts** [comment]
Found the source of problem, will be fixed in 1.7.4.

**Comment by igorkis-scrts** [comment]
Fixed in 1.7.4.
