### ISSUE TITLE
[Change Request]: Construction

### ISSUE THREAD

**Issue by TheOfficialDroid** [igorkis-scrts/A3-Antistasi-Plus#57]
### Is the requested change related to a problem?

No

### Describe the solution you'd like.

Option to disable or alter the "safe" grid to allow for more finite control; For things such as bunkers, walls and so on; So they don't have massive gaps.

### Alternative solutions

No other alternative other than adding another system.

### Additional context

The placement safe grid is way too big; Being unable to clip walls into eachother or place them side by side reliably is somewhat frustrating.

**Comment by igorkis-scrts** [comment]
In a meantime you could use SHIFT key for more precise placement.
Also, i will add 1-to-1 position mode to SHIFT key functionality for building placement type in the next patch.

**Comment by igorkis-scrts** [comment]
Fixed in 1.7.4.
