### ISSUE TITLE
[Bug]: Garaged vehicles don't send inventory to the arsenal

### ISSUE THREAD

**Issue by LemonXVI** [igorkis-scrts/A3-Antistasi-Plus#60]
### Describe the bug

When garaging vehicles their stored items are not being sent to the arsenal. The inventory of the vehicle is cleared as usual when brought back out of the garage.

### How to reproduce

Garage any vehicle.

### Version

1.7.3

### Have you altered the code?

No

### Map

Virolahti

### What server?

LAN Hosted

### Mods

```html
CBA_A3	Steam
Blastcore Edited (standalone version)	Steam
Cartridge Cases	Steam
Enhanced Movement	Steam
RHSAFRF	Steam
RHSUSAF	Steam
JSRS SOUNDMOD	Steam
LAMBS_RPG	Steam
LAMBS_Suppression	Steam
Advanced Towing	Steam
Advanced Sling Loading	Steam
ace	Steam
RHSSAF	Steam
RHSGREF	Steam
Enhanced GPS	Steam
Bloodlust LITE	Steam
ACRE2	Steam
Dual Arms - Two Primary Weapons	Steam
CUP Terrains - Core	Steam
JSRS SOUNDMOD - Reloading Sounds	Steam
JSRS SOUNDMOD - RHS AiO Mod Pack Sound Support	Steam
BettIR (Legacy v0.2.1)	Steam
Gruppe Adler Trenches	Steam
LAMBS_Danger.fsm	Steam
Align	Steam
Immerse	Steam
No More Aircraft Bouncing	Steam
Freestyles Crash Landing	Steam
Achilles	Steam
ACEX	Steam
Advanced Rappelling - Reworked	Steam
Helicopter Turbulence	Steam
ACE Compat - RHS Armed Forces of the Russian Federation	Steam
ACE Compat - RHS United States Armed Forces	Steam
ACE Compat - RHS: GREF	Steam
ACE Compat - RHS: SAF	Steam
Suppress	Steam
LAMBS_RPG_RHS	Steam
ACRE Animations	Steam
Arma 3 Performance Extension	Steam
3CB Factions	Steam
Enhanced Soundscape	Steam
Virolahti - Valtatie 7	Steam
CUP ACE3 Compatibility Addon - Terrains	Steam
Prone Launcher	Steam
```

**Comment by igorkis-scrts** [comment]
Thanks for report.

Also, Remove Freestyles Crash Landing and Arma FPS Extension - it breaks the mission.

**Comment by LemonXVI** [comment]
> Thanks for report.
> 
> Also, Remove Freestyles Crash Landing and Arma FPS Extension - it breaks the mission.
Alright, didn't know about that. Haven't run into any problems.

**Comment by LemonXVI** [comment]
> Thanks for report.
> 
> Also, Remove Freestyles Crash Landing and Arma FPS Extension - it breaks the mission.

**Comment by LemonXVI** [comment]
> Thanks for report.
> 
> Also, Remove Freestyles Crash Landing and Arma FPS Extension - it breaks the mission.

Alright, I didn't know about that, although I haven't run into any apparent issues with it.

**Comment by igorkis-scrts** [comment]
Also, unfortunately, i can't do anything about new garage as it is distributed under APL-ND (Arma Public License - No Deriatives) license which prohibits distribution of any modifications of original code.

[APL-ND](https://www.bohemia.net/community/licenses/arma-public-license-nd)
