### ISSUE TITLE
No entry 'bin\config.bin/CfgWorlds.Panthera'

### ISSUE THREAD

**Issue by misterfunkton** [igorkis-scrts/A3-Antistasi-Plus#65]
### Describe the bug

I have been trying to get the Antistasi Plus - Panthera mission to work on a gamehost server I recently purchased.

For some reason, the mission is unable to find Panthera

### How to reproduce

I downloaded the map, mission, and CUP files directly to the dedicated server via workshop. 

### Version

1.7.3

### Have you altered the code?

Yes

### What i have changed

```markdown
In the terrain folder for Panthera I renamed the 'Addons' folder to 'addons' because it was preventing my gamehost from detecting the mod.

Aside from this I have altered nothing.
```

### Map

Panthera

### What server?

Private dedicated server

### Mods

```html
-mod=@CBA_A3;@Island_Panthera;@CUP_Core;@CUP_Terrains_Maps;
```

### Additional context

[arma3server_2021-09-20_10-34-36.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/7196542/arma3server_2021-09-20_10-34-36.txt)
[server.txt](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/7196571/server.txt)

**Comment by igorkis-scrts** [comment]
This has nothing to do with Antistasi. It's because you have renamed mission postfix. It should be `.pathera3`, not `.Panthera`. Arma 3 detects `worldName` on map postfix, so changing it may break things.
