### ISSUE TITLE
AI spawning in a pile and not moving

### ISSUE THREAD

**Issue by Fuggschen** [igorkis-scrts/A3-Antistasi-Plus#76]
**Describe the bug**
Spawned AI won't move in outposts or roadblocks to normal positions. AI also won't point their weapon onto the player while shooting or turn around to "see" the player

**To Reproduce**
Can't really tell how to repoduce. Find a foe roadblock or spawn AI via commander menu in your outpost

**Expected behaviour**
AI should move away from their pile and go into formation. They should also look and point their weapon at the player or other AI while shooting

**Screenshots**
https://imgur.com/a/YUun5jQ

**Environment (please complete the following information):**
Version: 2.5.3 / 1.8.3.1
Map: Altis

* [ ] LAN Hosted
* [X] Private dedicated server
* [X] Private dedicated server with Headless client(s)

Modset:
* Advanced Sling Loading
* Advanced Towing
* Advanced Urban Rappelling
* CBA_A3
* Enhanced Movement
* Enhanced Movement Rework
* Improved Melee System
* No More Aircraft Bouncing
* RHSAFRF
* RHSUSAF
* RHSGREF
* RHSPKL
* RHSSAF
* Task Force Timberwolf Female Characters
* Vehicle Door Actions
* Arsenal Search
* Blastcore Edited (standalone version)
* DynaSound 2
* Enhanced Missile Smoke + Lighting Efx Mod v1.4
* Enhanced Soundscape
* Enhanced Weather + Clouds Mod v2.1
* Helicopter Dust Efx Mod
* Reduced Haze Mod v3.1

**Comment by Fuggschen** [comment]
Also tried now with less mods (only RHS and CBA) and it still happens

**Comment by Fuggschen** [comment]
Thanks for replying this fast :D
We were only in [this part of Altis](https://imgur.com/1fsld3x) and it was on every outpost. It doesn't only affects spawned garrison AI but also USAF and AFRF AI. Also [recorded this piece](https://youtu.be/sZlTPDq6vOI) how "stupid" it looks

**Comment by igorkis-scrts** [comment]
![20220808193740_1](https://user-images.githubusercontent.com/6746043/183468942-d07d436a-7a3c-4b67-8b32-d6e6b2202eaf.jpg)
![20220808193806_1](https://user-images.githubusercontent.com/6746043/183468947-0ba56daa-60b7-4021-909b-298293339963.jpg)

Can't reproduce this either on dedicated or listen server - everything works normal as shown on screeshots above. Looks like it's not an Antistasi Plus issue but a server, network or mod configuration one.  I suggest you to check which settings and mods your private dedicated server uses - many "performance", graphics enhacements, special effects or AI mods may break the game in the ways you can't imagine.  
You could play with base modset (seems to be 3CBF+RHS) and add mods one by one.

**Comment by Fuggschen** [comment]
Found the mod thats creating this issue: [Advanced Urban Rappelling](https://steamcommunity.com/sharedfiles/filedetails/?id=730310357)
Didn't noticed it on other missions or zeus missions so I was thinking it had to be a mission error.

Thanks for checking and fast responding! We will now have a great time at Altis :D
