### ISSUE TITLE
[Feature Request]: Requesting close air support

### ISSUE THREAD

**Issue by Mayoringram** [igorkis-scrts/A3-Antistasi-Plus#78]
### Related problem

We are playing your Antistasi Plus as 2-3 people per session and none of us are good at controlling a plane nor helis around.

### Proposed feature

There are bombing support implemented already I know but is there any chance of adding maybe requesting a gunship "we captured before and in garage" to be used as a CAS? AI will give us support as we advance.

**Comment by igorkis-scrts** [comment]
Yeah, it's a great idea, maybe some day it will be implemented.
