### ISSUE TITLE
Weapon "unlock" issue

### ISSUE THREAD

**Issue by LtGen-Slayer** [igorkis-scrts/A3-Antistasi-Plus#79]
Log for weapons unlocking in the arsenal every time something is garaged, saved, or taxed

[arma3server_x64_2022-09-03_21-50-48.zip](https://github.com/igorkis-scrts/A3-Antistasi-Plus/files/9484379/arma3server_x64_2022-09-03_21-50-48.zip)

**Comment by igorkis-scrts** [comment]
Unfortunately, it does not contain strings about weapon unlock is these will be shown only in DEBUG severity log mode.
Anyway, as I said it before the reason of this behaviour is very likely the usage of unsupported mods.
