### ISSUE TITLE
Arms Dealer Over price

### ISSUE THREAD

**Issue by asumadelta** [igorkis-scrts/A3-Antistasi-Plus#8]
**What, in your opinion, is currently wrong with the balance?**
when compare to income , army cost  and  vehicle price that can see all weapons in Arms Dealer is over price

EX 1.
1 assault rifle not include ammo  800-2300 $
compare to  1 small operation cost about  2000-3000 $  include( 16 man and 1 mortar team)
compare to  1 HMG vehicle cost 1000$  (off road M2  .50cal include 300-400 round of ammo) 

Ex 2.
1 RPG-7V2   not include ammo 1500$
compare to 1 AT vehicle   cost 1500$ (off road SPG include 20 round of ammo) 
disassemble cost  1 off road   350$  that mean weapons cost (1500-350) = 1150 $
compare to RPG-7V2 + 20 round of ammo + optic  (1500+(300*20)+400) = 7900 $

**Describe the solution you'd like**
lower price of Arms Deale 70% - 90%

**Comment by igorkis-scrts** [comment]
Thanks for report, prices will be lowered in **1.4.1**.

**Comment by Randomisation** [comment]
Honestly, I don't think the weapons are overpriced. I think the vehicles and squads are underpriced.
