### ISSUE TITLE
[Feature Request]: Any plans for IFA3 support?

### ISSUE THREAD

**Issue by MixedMethods** [igorkis-scrts/A3-Antistasi-Plus#82]
### Related problem

Pretty much as title says!

### Proposed feature

Apologies if this has been requested elsewhere!

**Comment by igorkis-scrts** [comment]
Unfortunately, no plans at all. I'm seeing all various problems with IFA3 support in Antistasi Ultimate, so I decided that it's not worth it.
WW2 support will come if it will come through some singular quality package as mod or CDLC.

**Comment by MixedMethods** [comment]
Understandable, thank you for the response!
