### ISSUE TITLE
[Bug]: Tura faction not working

### ISSUE THREAD

**Issue by mongchat** [igorkis-scrts/A3-Antistasi-Plus#87]
### Describe the bug

When I select Sefrou-Ramal and choose Tura as the rebel faction, it gets stuck on "Starting the game..." popup in the top right corner. it eventually fades out, but neither petros nor any of the crates necessary spawn. When I select FIA on Sefrou-Ramal it works fine

### How to reproduce

Load into Sefrou-Ramal and select Tura as rebel faction, then click start (self explanatory but this box was mandatory lol)

### Version

Latest

### Have you altered the code?

No

### Map

Sefrou-Ramal

### What server?

LAN Hosted

### Mods

```html
No mods other than Antistasi Plus 2.0
```

**Comment by igorkis-scrts** [comment]
Tested it - it works.
Could you provide .rpt log?

```
An RPT is a log that is being created by the game and contains a ton of useful information we can use to find out if something went wrong and if so, what went wrong.
There are different types of RPTs being created but you are always looking for the one named with following pattern:
Arma3_x64_2021-05-16_16-39-01.rpt

The file can usually be found in your C:\Users\[USER]\AppData\Local\Arma 3 folder.
Make sure that you send the one that contains the issue you would like to report/else.
```

**Comment by igorkis-scrts** [comment]
Found the issue, thanks for report.
