### ISSUE TITLE
[Change Request]: Change the server sided nature of the loadout saving system

### ISSUE THREAD

**Issue by MattyMartholomew** [igorkis-scrts/A3-Antistasi-Plus#88]
### Is the requested change related to a problem?

When attempting to create a load out, with weapons, armor, etc. Saving it requires the server host to save the mission. the old version allowed any saves from single player or whatever to be used and not rely on the server host themselves. Is there a work around or is this an intended feature 

### Describe the solution you'd like.

Replace the system for saving load outs with the old one that allows players to bring loadouts from single player or other antistasi sessions. Instead of requiring a server save everytime a new player makes a new loadout

**Comment by MattyMartholomew** [comment]
like actually unplayable, lucky there is no dislike button on steam

**Comment by igorkis-scrts** [comment]
Thanks for report, I'll take a look at that.

**Comment by igorkis-scrts** [comment]
Fixed in 2.0.0.42c12ae.
