### ISSUE TITLE
[Bug]: when creating a loadout and pressing save, when reloading to the server the save has vanished. even after just aborting to the class select screen

### ISSUE THREAD

**Issue by MattyMartholomew** [igorkis-scrts/A3-Antistasi-Plus#89]
### Describe the bug

When creating a loadout, and leaving the server to pee or eat or whatever, the loadout gets launched into the xenosphere and is forced to be re made. Wouldn't be as huge an issue if I wasn't using ace medical. But it's been a large pain in the butt and a deterrent from playing your wonderful mod. 

### How to reproduce

Make a loadout and then save it. Leave the server and re join, it's gone

### Version

most recent one 

### Have you altered the code?

No

### Map

chenarus 2020

### What server?

Private dedicated server with Headless client(s)

**Comment by igorkis-scrts** [comment]
Isn't you already created the ticket about this yesterday?

It's already fixed in today's hotfix. If you're still encountering this issue - unsubscribe and then resubscribe to the mod, seems that you're still on older version.

**Comment by MattyMartholomew** [comment]
Hey thanks for the speedy replies, myself and all 4 of my mates had uninstalled and reinstalled the mod from our devices and the server itself, with a fresh launch of the mod were still running into the issue. Could have been steam being slow. But the arma launcher did say that it had been "updated"
