### ISSUE TITLE
AI doesn't seem to be very active on Chernarus map[Bug]: 

### ISSUE THREAD

**Issue by Vereenn** [igorkis-scrts/A3-Antistasi-Plus#90]
### Describe the bug

We've been playing with the 2.0 version on Chernarus 2020 map first on easy difficulty, then we changed it to normal mid-mission. On both of these AI is barely reacting to our activities. We have War Level 4, and during our last session we took one of Military Bases only to be met with absolutely no response from the AI. Not a single QRF or counterattack. When compared to our campaign on Isla Abramia from previous version of the mission which we played on easy difficulty the AI is non-existent. On Abramia they would send 5-10 choppers after conquering an outpost or a base, which was too much, but now they don't send enough and the mission seems to be too easy. We have like 1/10 of the map and the biggest response we saw was 1 chopper with 1 squad. I am not sure if this is a bug or if this is new normal.

### How to reproduce

Start a campaign on Chernarus 2020 map.

### Version

2.0

### Have you altered the code?

No

### Map

Chernarus 2020

### What server?

Private dedicated server

### Mods

```html
@CBA_A3;@Zeus Enhanced;@Advanced Rappelling;@Advanced Urban Rappelling;@Advanced Sling Loading;@Advanced Towing;@Enhanced Movement;@RHSGREF;@RHSAFRF;@RHSUSAF;@RHRM [REAL HERO's RAGDOLL MOD];@Zeus Enhanced - ACE3 Compatibility;@CUP Terrains - Core;@3CB Factions;@ace 3.15;@Enhanced Movement Rework;@Isla Abramia;@Loot to Vehicle for ACE and Antistasi;@RHSSAF;@Antistasi Plus 2.0;@CUP Terrains - Maps 2.0
```

**Comment by igorkis-scrts** [comment]
You could increase enemy capabilities via balance section in Params tab.
Yeah, enemy responses are lighter up to 5 level, they become harsher as war progresses.

**Comment by Vereenn** [comment]
> You could increase enemy capabilities via balance section in Params tab. Yeah, enemy responses are lighter up to 5 level, they become harsher as war progresses.

Thanks for such a quick reply, we will tinker with the settings more then. Keep up the great work, your Antistasi is definitely the best one out there, thanks for giving us hours and hours of fun!
