### ISSUE TITLE
No backpacks allow going undercover (even in vehicles)

### ISSUE THREAD

**Issue by Tzimovo** [igorkis-scrts/A3-Antistasi-Plus#96]
Hi, 

there seems to be an issue where I can't go under cover wearing any of the backpacks I tested. Even the civilian Backpacks don't seem to allow going undercover - not even in vehicles. Default backpacks that were available from the start also don't work.

Civilian Backpacks I tried by adding them manually were: Messenger bags, a Hiking Backpack, and some Engineer backpack that looked pretty civilian at least. :)

I am running the mod on a Linux dedicated server with 3cb-factions, RHS and Ace (some more mods but I doubt they would affect the ability to go under cover or the equipment available). I can allow access to the server for verification.

Cheers,
Tzi

**Comment by igorkis-scrts** [comment]
@Tzimovo 
Adding backpacks off-systems (via console or zeus) will not work as they will be not registered as civ backpacks by mod code. Black assault pack and messenger backpacks are civilian, but they should be added via game. Guess you have not ticked DLC checkbockes (at Laws Of War will add Messenger backpacks which considered to be civilian ones).

**Comment by Tzimovo** [comment]
Hmm thanks for the quick info, I think I did check all DLC's but I'll try again. The messenger bag was not included automatically so I may have forgotten the tick mark on the DLC and I'll check again of hte black assault pack was added automatically.

**Comment by mongchat** [comment]
civilian cars intentionally no longer make you undercover to nerf it (you used to be able to stand on the back of an offroad with an RPG in front of a patrol without being suspicious). if you're the driver you just need to remove chest-rigs and helmets then manually select "Go Undercover". passengers need to remove chest-rigs, helmets, and all weapons into the inventory of the vehicle then manually select "Go Undercover". AI in the vehicle will automatically do it when the driver does

**Comment by Tzimovo** [comment]
Ok, it's an intentional change then, I'll close the report again. Thanks for the heads up, I must have overlooked that change.
