### ISSUE TITLE
[Bug]: Military Administration building staircase too high for players/AI on Sefrou-Ramal

### ISSUE THREAD

**Issue by mongchat** [igorkis-scrts/A3-Antistasi-Plus#97]
### Describe the bug

The Military Administration building in Bir Dakhla in the middle of Sefrou-Ramal is placed too high for players to access correctly from one side. This also affects the ability of friendly AI to enter the building without clipping under the floor.

Appreciably there's not much flat ground to work with here, I'm not sure how best to alter it to work, but I've noticed friendly AI glitching under the floor trying to enter through the door with the raised stairs. Not a very major issue but just something to consider.

![AdminAlt](https://user-images.githubusercontent.com/106987485/212739380-13a69e19-85f5-45ee-9adf-13f146a452b5.png)
![AdminGlitched](https://user-images.githubusercontent.com/106987485/212739398-fff0e5bb-c8de-40fa-88f5-7a12266fc27b.png)
![Adminmap](https://user-images.githubusercontent.com/106987485/212739418-9e32c287-cdec-4d64-8b3f-5c716a94f9d5.png)

### How to reproduce

Load Sefrou-Ramal and try to get AI or players to enter. They should glitch underneath the floor.

### Version

2.0.2

### Have you altered the code?

No

### Map

Sefrou-Ramal

### What server?

LAN Hosted

**Comment by igorkis-scrts** [comment]
Fixed in 2.1.
