### ISSUE TITLE
[Bug]: Huron fuel containers despawn on mission restart

### ISSUE THREAD

**Issue by Drift91** [igorkis-scrts/A3-Antistasi-Plus#99]
### Describe the bug

If you buy a Huron fuel container and then restart the mission, the fuel container will not persist and will despawn.

### How to reproduce

Buy a Huron fuel container.
Make a persistent save.
Restart the mission and load the save.
Look where the Huron fuel container was.

### Version

2.0.2

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted, Private dedicated server

### Mods

```html
"-mod=@CBA_A3;@Antistasi Plus 2.0;@RHSAFRF;@RHSUSAF;@RHSGREF;@RHSSAF;@3CB Factions"
```

**Comment by Drift91** [comment]
Seems like the same issue applies to the "buy light" option. The lamppost will despawn upon mission restart instead of persisting.

**Comment by igorkis-scrts** [comment]
All these items are not persistent and it's intentional (same as loot crates, for example).
